package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1
// Updated Jan 3, 2015 2:16 PM by space.wen@wolaidai.com

import java.math.BigDecimal;
import java.util.Date;

/**
 * Accounts generated by hbm2java
 */
public class Account implements java.io.Serializable
{
	private static final long serialVersionUID = 7207917925646956528L;
	public static final Integer DEFAULT_CREDIT_LINE = 3000;

	private Integer id;
	private Integer owner_id;
	private String owner_type;
	private BigDecimal balance;
	private Date created_at;
	private Date updated_at;
	private BigDecimal cash_balance;
	private BigDecimal freeze_balance;
	private BigDecimal credit_line;
	//
	private BigDecimal maximum_withdraw_amount;
	private Integer available_credit_line;
	private BigDecimal reward_balance;

	public Account()
	{}

	public Account(Integer id)
	{
		this.id = id;
	}

	public Account(Integer id, Integer ownerId, String ownerType, BigDecimal balance, Date createdAt, Date updatedAt,
			BigDecimal cashBalance, BigDecimal rewardBalance, BigDecimal freezeBalance, BigDecimal creditLine)
	{
		this.id = id;
		this.owner_id = ownerId;
		this.owner_type = ownerType;
		this.balance = balance;
		this.created_at = createdAt;
		this.updated_at = updatedAt;
		this.cash_balance = cashBalance;
		this.reward_balance = rewardBalance;
		this.freeze_balance = freezeBalance;
		this.credit_line = creditLine;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public BigDecimal getBalance()
	{
		return this.balance;
	}

	public void setBalance(BigDecimal balance)
	{
		this.balance = balance;
	}

	public BigDecimal getMaximum_withdraw_amount()
	{
		return maximum_withdraw_amount;
	}

	public void setMaximum_withdraw_amount(BigDecimal maximum_withdraw_amount)
	{
		this.maximum_withdraw_amount = maximum_withdraw_amount;
	}

	public Integer getAvailable_credit_line()
	{
		return available_credit_line;
	}

	public void setAvailable_credit_line(Integer available_credit_line)
	{
		this.available_credit_line = available_credit_line;
	}

	public Integer getOwner_id()
	{
		return owner_id;
	}

	public void setOwner_id(Integer owner_id)
	{
		this.owner_id = owner_id;
	}

	public String getOwner_type()
	{
		return owner_type;
	}

	public void setOwner_type(String owner_type)
	{
		this.owner_type = owner_type;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

	public BigDecimal getCash_balance()
	{
		return cash_balance;
	}

	public void setCash_balance(BigDecimal cash_balance)
	{
		this.cash_balance = cash_balance;
	}

	public BigDecimal getReward_balance()
	{
		return reward_balance;
	}

	public void setReward_balance(BigDecimal reward_balance)
	{
		this.reward_balance = reward_balance;
	}

	public BigDecimal getFreeze_balance()
	{
		return freeze_balance;
	}

	public void setFreeze_balance(BigDecimal freeze_balance)
	{
		this.freeze_balance = freeze_balance;
	}

	public BigDecimal getCredit_line()
	{
		return credit_line;
	}

	public void setCredit_line(BigDecimal credit_line)
	{
		this.credit_line = credit_line;
	}

}
