package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AccountTransactions generated by hbm2java
 */
public class AccountTransaction implements java.io.Serializable
{
	private static final long serialVersionUID = 4501824397719257658L;
	private Integer id;
	private Integer account_id;
	private BigDecimal amount;
	private String transaction_code;
	private Integer creator_id;
	private Integer reverse_to;
	private Date created_at;
	private Date updated_at;
	private Integer loan_id;
	private String action;
	private BigDecimal cash_balance;
	private String channel_type;
	private Integer channel_id;

	public AccountTransaction()
	{}

	public AccountTransaction(Integer id)
	{
		this.id = id;
	}

	public AccountTransaction(Integer id, Integer accountId, BigDecimal amount, String transactionCode,
			Integer creatorId, Integer reverseTo, Date createdAt, Date updatedAt, Integer loanId, String action,
			BigDecimal cashBalance, String channelType, Integer channelId)
	{
		this.id = id;
		this.account_id = accountId;
		this.amount = amount;
		this.transaction_code = transactionCode;
		this.creator_id = creatorId;
		this.reverse_to = reverseTo;
		this.created_at = createdAt;
		this.updated_at = updatedAt;
		this.loan_id = loanId;
		this.action = action;
		this.cash_balance = cashBalance;
		this.channel_type = channelType;
		this.channel_id = channelId;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getAccount_id()
	{
		return account_id;
	}

	public void setAccount_id(Integer account_id)
	{
		this.account_id = account_id;
	}

	public BigDecimal getAmount()
	{
		return amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public String getTransaction_code()
	{
		return transaction_code;
	}

	public void setTransaction_code(String transaction_code)
	{
		this.transaction_code = transaction_code;
	}

	public Integer getCreator_id()
	{
		return creator_id;
	}

	public void setCreator_id(Integer creator_id)
	{
		this.creator_id = creator_id;
	}

	public Integer getReverse_to()
	{
		return reverse_to;
	}

	public void setReverse_to(Integer reverse_to)
	{
		this.reverse_to = reverse_to;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

	public Integer getLoan_id()
	{
		return loan_id;
	}

	public void setLoan_id(Integer loan_id)
	{
		this.loan_id = loan_id;
	}

	public String getAction()
	{
		return action;
	}

	public void setAction(String action)
	{
		this.action = action;
	}

	public BigDecimal getCash_balance()
	{
		return cash_balance;
	}

	public void setCash_balance(BigDecimal cash_balance)
	{
		this.cash_balance = cash_balance;
	}

	public String getChannel_type()
	{
		return channel_type;
	}

	public void setChannel_type(String channel_type)
	{
		this.channel_type = channel_type;
	}

	public Integer getChannel_id()
	{
		return channel_id;
	}

	public void setChannel_id(Integer channel_id)
	{
		this.channel_id = channel_id;
	}

}
