package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Addresses generated by hbm2java
 */
public class Addresses implements java.io.Serializable
{

	private static final long serialVersionUID = -4633970630943440161L;
	private Integer id;
	private Integer province;
	private Integer city;
	private Integer district;
	private String street;
	private String location;
	private String telephone;
	private Integer addressable_id;
	private String addressable_type;
	private Date created_at;
	private Date updated_at;

	public Addresses()
	{}

	public Addresses(Integer id)
	{
		this.id = id;
	}

	public Addresses(int id, Integer province, Integer city, Integer district, String street, String location,
			String telephone, Integer addressableId, String addressableType, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.province = province;
		this.city = city;
		this.district = district;
		this.street = street;
		this.location = location;
		this.telephone = telephone;
		this.addressable_id = addressableId;
		this.addressable_type = addressableType;
		this.created_at = createdAt;
		this.updated_at = updatedAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getProvince()
	{
		return this.province;
	}

	public void setProvince(Integer province)
	{
		this.province = province;
	}

	public Integer getCity()
	{
		return this.city;
	}

	public void setCity(Integer city)
	{
		this.city = city;
	}

	public Integer getDistrict()
	{
		return this.district;
	}

	public void setDistrict(Integer district)
	{
		this.district = district;
	}

	public String getStreet()
	{
		return this.street;
	}

	public void setStreet(String street)
	{
		this.street = street;
	}

	public String getLocation()
	{
		return this.location;
	}

	public void setLocation(String location)
	{
		this.location = location;
	}

	public String getTelephone()
	{
		return this.telephone;
	}

	public void setTelephone(String telephone)
	{
		this.telephone = telephone;
	}

	public Integer getAddressable_id()
	{
		return addressable_id;
	}

	public void setAddressable_id(Integer addressable_id)
	{
		this.addressable_id = addressable_id;
	}

	public String getAddressable_type()
	{
		return addressable_type;
	}

	public void setAddressable_type(String addressable_type)
	{
		this.addressable_type = addressable_type;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

}
