package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1
// Updated Jan 3, 2015 2:16 PM by space.wen@wolaidai.com

import java.util.Date;

/**
 * Admins generated by hbm2java
 */
public class Admin implements java.io.Serializable
{
	private static final long serialVersionUID = -8469701618475850166L;
	private Integer id;
	private String email;
	private String encryptedPassword;
	private int signInCount;
	private Date currentSignInAt;
	private Date lastSignInAt;
	private String currentSignInIp;
	private String lastSignInIp;
	private int failedAttempts;
	private String unlockToken;
	private Date lockedAt;
	private String mobile;
	private Date createdAt;
	private Date updatedAt;
	private String otpSecretKey;
	private Integer secondFactorAttemptsCount;
	private String role;
	private String invitationToken;
	private Date invitationCreatedAt;
	private Date invitationSentAt;
	private Date invitationAcceptedAt;
	private Integer invitationLimit;
	private Integer invitedById;
	private String invitedByType;
	private Integer invitationsCount;
	private Date lastAssignedAt;

	public Admin()
	{}

	public Admin(Integer id, String email, int signInCount, int failedAttempts)
	{
		this.id = id;
		this.email = email;
		this.signInCount = signInCount;
		this.failedAttempts = failedAttempts;
	}

	public Admin(Integer id, String email, String encryptedPassword, int signInCount, Date currentSignInAt,
			Date lastSignInAt, String currentSignInIp, String lastSignInIp, int failedAttempts, String unlockToken,
			Date lockedAt, String mobile, Date createdAt, Date updatedAt, String otpSecretKey,
			Integer secondFactorAttemptsCount, String role, String invitationToken, Date invitationCreatedAt,
			Date invitationSentAt, Date invitationAcceptedAt, Integer invitationLimit, Integer invitedById,
			String invitedByType, Integer invitationsCount)
	{
		this.id = id;
		this.email = email;
		this.encryptedPassword = encryptedPassword;
		this.signInCount = signInCount;
		this.currentSignInAt = currentSignInAt;
		this.lastSignInAt = lastSignInAt;
		this.currentSignInIp = currentSignInIp;
		this.lastSignInIp = lastSignInIp;
		this.failedAttempts = failedAttempts;
		this.unlockToken = unlockToken;
		this.lockedAt = lockedAt;
		this.mobile = mobile;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.otpSecretKey = otpSecretKey;
		this.secondFactorAttemptsCount = secondFactorAttemptsCount;
		this.role = role;
		this.invitationToken = invitationToken;
		this.invitationCreatedAt = invitationCreatedAt;
		this.invitationSentAt = invitationSentAt;
		this.invitationAcceptedAt = invitationAcceptedAt;
		this.invitationLimit = invitationLimit;
		this.invitedById = invitedById;
		this.invitedByType = invitedByType;
		this.invitationsCount = invitationsCount;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getEncryptedPassword()
	{
		return this.encryptedPassword;
	}

	public void setEncryptedPassword(String encryptedPassword)
	{
		this.encryptedPassword = encryptedPassword;
	}

	public int getSignInCount()
	{
		return this.signInCount;
	}

	public void setSignInCount(int signInCount)
	{
		this.signInCount = signInCount;
	}

	public Date getCurrentSignInAt()
	{
		return this.currentSignInAt;
	}

	public void setCurrentSignInAt(Date currentSignInAt)
	{
		this.currentSignInAt = currentSignInAt;
	}

	public Date getLastSignInAt()
	{
		return this.lastSignInAt;
	}

	public void setLastSignInAt(Date lastSignInAt)
	{
		this.lastSignInAt = lastSignInAt;
	}

	public String getCurrentSignInIp()
	{
		return this.currentSignInIp;
	}

	public void setCurrentSignInIp(String currentSignInIp)
	{
		this.currentSignInIp = currentSignInIp;
	}

	public String getLastSignInIp()
	{
		return this.lastSignInIp;
	}

	public void setLastSignInIp(String lastSignInIp)
	{
		this.lastSignInIp = lastSignInIp;
	}

	public int getFailedAttempts()
	{
		return this.failedAttempts;
	}

	public void setFailedAttempts(int failedAttempts)
	{
		this.failedAttempts = failedAttempts;
	}

	public String getUnlockToken()
	{
		return this.unlockToken;
	}

	public void setUnlockToken(String unlockToken)
	{
		this.unlockToken = unlockToken;
	}

	public Date getLockedAt()
	{
		return this.lockedAt;
	}

	public void setLockedAt(Date lockedAt)
	{
		this.lockedAt = lockedAt;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public String getOtpSecretKey()
	{
		return this.otpSecretKey;
	}

	public void setOtpSecretKey(String otpSecretKey)
	{
		this.otpSecretKey = otpSecretKey;
	}

	public Integer getSecondFactorAttemptsCount()
	{
		return this.secondFactorAttemptsCount;
	}

	public void setSecondFactorAttemptsCount(Integer secondFactorAttemptsCount)
	{
		this.secondFactorAttemptsCount = secondFactorAttemptsCount;
	}

	public String getRole()
	{
		return this.role;
	}

	public void setRole(String role)
	{
		this.role = role;
	}

	public String getInvitationToken()
	{
		return this.invitationToken;
	}

	public void setInvitationToken(String invitationToken)
	{
		this.invitationToken = invitationToken;
	}

	public Date getInvitationCreatedAt()
	{
		return this.invitationCreatedAt;
	}

	public void setInvitationCreatedAt(Date invitationCreatedAt)
	{
		this.invitationCreatedAt = invitationCreatedAt;
	}

	public Date getInvitationSentAt()
	{
		return this.invitationSentAt;
	}

	public void setInvitationSentAt(Date invitationSentAt)
	{
		this.invitationSentAt = invitationSentAt;
	}

	public Date getInvitationAcceptedAt()
	{
		return this.invitationAcceptedAt;
	}

	public void setInvitationAcceptedAt(Date invitationAcceptedAt)
	{
		this.invitationAcceptedAt = invitationAcceptedAt;
	}

	public Integer getInvitationLimit()
	{
		return this.invitationLimit;
	}

	public void setInvitationLimit(Integer invitationLimit)
	{
		this.invitationLimit = invitationLimit;
	}

	public Integer getInvitedById()
	{
		return this.invitedById;
	}

	public void setInvitedById(Integer invitedById)
	{
		this.invitedById = invitedById;
	}

	public String getInvitedByType()
	{
		return this.invitedByType;
	}

	public void setInvitedByType(String invitedByType)
	{
		this.invitedByType = invitedByType;
	}

	public Integer getInvitationsCount()
	{
		return this.invitationsCount;
	}

	public void setInvitationsCount(Integer invitationsCount)
	{
		this.invitationsCount = invitationsCount;
	}

	public Date getLastAssignedAt()
	{
		return lastAssignedAt;
	}

	public void setLastAssignedAt(Date lastAssignedAt)
	{
		this.lastAssignedAt = lastAssignedAt;
	}

}
