package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdminsRoles generated by hbm2java
 */
public class AdminsRoles implements java.io.Serializable
{

	private int id;
	private Integer adminId;
	private Integer roleId;
	private Date createdAt;
	private Date updatedAt;

	public AdminsRoles()
	{}

	public AdminsRoles(int id)
	{
		this.id = id;
	}

	public AdminsRoles(int id, Integer adminId, Integer roleId, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.adminId = adminId;
		this.roleId = roleId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getAdminId()
	{
		return this.adminId;
	}

	public void setAdminId(Integer adminId)
	{
		this.adminId = adminId;
	}

	public Integer getRoleId()
	{
		return this.roleId;
	}

	public void setRoleId(Integer roleId)
	{
		this.roleId = roleId;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
