package com.wolaidai.ws.jrocket2.persistence;

// Generated Jan 3, 2015 2:18:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AgentProfiles generated by hbm2java
 */
public class AgentProfile implements java.io.Serializable
{
	private static final long serialVersionUID = 2062348622004059900L;
	private Integer id;
	private String name;
	private String mobile;
	private String cnid;
	private Integer province;
	private Integer city;
	private Integer school;
	private Integer bank;
	private String card;
	private String email;
	private BigDecimal salary;
	private String spread;
	private Date enrollAt;
	private Date createdAt;
	private Date updatedAt;

	public AgentProfile()
	{}

	public AgentProfile(Integer id)
	{
		this.id = id;
	}

	public AgentProfile(Integer id, String name, String mobile, String cnid, Integer province, Integer city,
			Integer school, Integer bank, String card, String email, BigDecimal salary, String spread, Date enrollAt,
			Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.name = name;
		this.mobile = mobile;
		this.cnid = cnid;
		this.province = province;
		this.city = city;
		this.school = school;
		this.bank = bank;
		this.card = card;
		this.email = email;
		this.salary = salary;
		this.spread = spread;
		this.enrollAt = enrollAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getCnid()
	{
		return this.cnid;
	}

	public void setCnid(String cnid)
	{
		this.cnid = cnid;
	}

	public Integer getProvince()
	{
		return this.province;
	}

	public void setProvince(Integer province)
	{
		this.province = province;
	}

	public Integer getCity()
	{
		return this.city;
	}

	public void setCity(Integer city)
	{
		this.city = city;
	}

	public Integer getSchool()
	{
		return this.school;
	}

	public void setSchool(Integer school)
	{
		this.school = school;
	}

	public Integer getBank()
	{
		return this.bank;
	}

	public void setBank(Integer bank)
	{
		this.bank = bank;
	}

	public String getCard()
	{
		return this.card;
	}

	public void setCard(String card)
	{
		this.card = card;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public BigDecimal getSalary()
	{
		return this.salary;
	}

	public void setSalary(BigDecimal salary)
	{
		this.salary = salary;
	}

	public String getSpread()
	{
		return this.spread;
	}

	public void setSpread(String spread)
	{
		this.spread = spread;
	}

	public Date getEnrollAt()
	{
		return this.enrollAt;
	}

	public void setEnrollAt(Date enrollAt)
	{
		this.enrollAt = enrollAt;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
