package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ApprovalChecklistItems generated by hbm2java
 */
public class ApprovalChecklistItems implements java.io.Serializable
{

	private int id;
	private Integer loanApplicationId;
	private String content;
	private Boolean checked;
	private Date createdAt;
	private Date updatedAt;

	public ApprovalChecklistItems()
	{}

	public ApprovalChecklistItems(int id)
	{
		this.id = id;
	}

	public ApprovalChecklistItems(int id, Integer loanApplicationId, String content, Boolean checked, Date createdAt,
			Date updatedAt)
	{
		this.id = id;
		this.loanApplicationId = loanApplicationId;
		this.content = content;
		this.checked = checked;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getLoanApplicationId()
	{
		return this.loanApplicationId;
	}

	public void setLoanApplicationId(Integer loanApplicationId)
	{
		this.loanApplicationId = loanApplicationId;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public Boolean getChecked()
	{
		return this.checked;
	}

	public void setChecked(Boolean checked)
	{
		this.checked = checked;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
