package com.wolaidai.ws.jrocket2.persistence;

// Generated Jan 3, 2015 2:18:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * Areas generated by hbm2java
 */
public class Area implements java.io.Serializable
{
	private static final long serialVersionUID = -3403466889264595168L;
	private Integer id;
	private String province_code;
	private String province_name;
	private String city_code;
	private Double city_level;
	private String city_name;
	private String district_code;
	private String district_name;

	public Area()
	{}

	public Area(Integer id)
	{
		this.id = id;
	}

	public Area(Integer id, String provinceCode, String provinceName, String cityCode, Double cityLevel,
			String cityName, String districtCode, String districtName)
	{
		this.id = id;
		this.province_code = provinceCode;
		this.province_name = provinceName;
		this.city_code = cityCode;
		this.city_level = cityLevel;
		this.city_name = cityName;
		this.district_code = districtCode;
		this.district_name = districtName;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getProvince_code()
	{
		return province_code;
	}

	public void setProvince_code(String province_code)
	{
		this.province_code = province_code;
	}

	public String getProvince_name()
	{
		return province_name;
	}

	public void setProvince_name(String province_name)
	{
		this.province_name = province_name;
	}

	public String getCity_code()
	{
		return city_code;
	}

	public void setCity_code(String city_code)
	{
		this.city_code = city_code;
	}

	public Double getCity_level()
	{
		return city_level;
	}

	public void setCity_level(Double city_level)
	{
		this.city_level = city_level;
	}

	public String getCity_name()
	{
		return city_name;
	}

	public void setCity_name(String city_name)
	{
		this.city_name = city_name;
	}

	public String getDistrict_code()
	{
		return district_code;
	}

	public void setDistrict_code(String district_code)
	{
		this.district_code = district_code;
	}

	public String getDistrict_name()
	{
		return district_name;
	}

	public void setDistrict_name(String district_name)
	{
		this.district_name = district_name;
	}

}
