package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * BlacklistsBorrowers generated by hbm2java
 */
public class BlacklistsBorrowers implements java.io.Serializable
{

	private BlacklistsBorrowersId id;

	public BlacklistsBorrowers()
	{}

	public BlacklistsBorrowers(BlacklistsBorrowersId id)
	{
		this.id = id;
	}

	public BlacklistsBorrowersId getId()
	{
		return this.id;
	}

	public void setId(BlacklistsBorrowersId id)
	{
		this.id = id;
	}

}
