package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CallRecords generated by hbm2java
 */
public class CallRecords implements java.io.Serializable
{

	private int id;
	private Integer loanApplicationId;
	private Integer adminId;
	private String message;
	private Date createdAt;
	private Date updatedAt;

	public CallRecords()
	{}

	public CallRecords(int id)
	{
		this.id = id;
	}

	public CallRecords(int id, Integer loanApplicationId, Integer adminId, String message, Date createdAt,
			Date updatedAt)
	{
		this.id = id;
		this.loanApplicationId = loanApplicationId;
		this.adminId = adminId;
		this.message = message;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getLoanApplicationId()
	{
		return this.loanApplicationId;
	}

	public void setLoanApplicationId(Integer loanApplicationId)
	{
		this.loanApplicationId = loanApplicationId;
	}

	public Integer getAdminId()
	{
		return this.adminId;
	}

	public void setAdminId(Integer adminId)
	{
		this.adminId = adminId;
	}

	public String getMessage()
	{
		return this.message;
	}

	public void setMessage(String message)
	{
		this.message = message;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
