package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CompanyDetails generated by hbm2java
 */
public class CompanyDetails implements java.io.Serializable
{

	private int id;
	private String name;
	private Integer districtId;
	private String street;
	private String phone;
	private Integer loanApplicationId;
	private Date createdAt;
	private Date updatedAt;

	public CompanyDetails()
	{}

	public CompanyDetails(int id)
	{
		this.id = id;
	}

	public CompanyDetails(int id, String name, Integer districtId, String street, String phone,
			Integer loanApplicationId, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.name = name;
		this.districtId = districtId;
		this.street = street;
		this.phone = phone;
		this.loanApplicationId = loanApplicationId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Integer getDistrictId()
	{
		return this.districtId;
	}

	public void setDistrictId(Integer districtId)
	{
		this.districtId = districtId;
	}

	public String getStreet()
	{
		return this.street;
	}

	public void setStreet(String street)
	{
		this.street = street;
	}

	public String getPhone()
	{
		return this.phone;
	}

	public void setPhone(String phone)
	{
		this.phone = phone;
	}

	public Integer getLoanApplicationId()
	{
		return this.loanApplicationId;
	}

	public void setLoanApplicationId(Integer loanApplicationId)
	{
		this.loanApplicationId = loanApplicationId;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
