package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Companies generated by hbm2java
 */
public class Companies implements java.io.Serializable
{

	private int id;
	private Integer userId;
	private String name;
	private String department;
	private String companyPosition;
	private Date entryTime;
	private Date departureTime;
	private Date createdAt;
	private Date updatedAt;

	public Companies()
	{}

	public Companies(int id)
	{
		this.id = id;
	}

	public Companies(int id, Integer userId, String name, String department, String companyPosition, Date entryTime,
			Date departureTime, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.userId = userId;
		this.name = name;
		this.department = department;
		this.companyPosition = companyPosition;
		this.entryTime = entryTime;
		this.departureTime = departureTime;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getDepartment()
	{
		return this.department;
	}

	public void setDepartment(String department)
	{
		this.department = department;
	}

	public String getCompanyPosition()
	{
		return this.companyPosition;
	}

	public void setCompanyPosition(String companyPosition)
	{
		this.companyPosition = companyPosition;
	}

	public Date getEntryTime()
	{
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime)
	{
		this.entryTime = entryTime;
	}

	public Date getDepartureTime()
	{
		return this.departureTime;
	}

	public void setDepartureTime(Date departureTime)
	{
		this.departureTime = departureTime;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
