package com.wolaidai.ws.jrocket2.persistence;

// Generated Jan 3, 2015 2:18:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CouponsUsers generated by hbm2java
 */
public class CouponsUser implements java.io.Serializable
{
	private static final long serialVersionUID = 7813127139273172073L;
	private Integer id;
	private Integer user_id;
	private Integer coupon_id;
	private Boolean redeemed;
	private Date created_at;
	private Date begin_at;
	private Date end_at;
	private Coupon coupon;

	public CouponsUser()
	{}

	public CouponsUser(Integer id)
	{
		this.id = id;
	}

	public CouponsUser(Integer id, Integer userId, Integer couponId, Boolean redeemed, Date createdAt, Date beginAt,
			Date endAt)
	{
		this.id = id;
		this.user_id = userId;
		this.coupon_id = couponId;
		this.redeemed = redeemed;
		this.created_at = createdAt;
		this.begin_at = beginAt;
		this.end_at = endAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Boolean getRedeemed()
	{
		return this.redeemed;
	}

	public void setRedeemed(Boolean redeemed)
	{
		this.redeemed = redeemed;
	}

	public Coupon getCoupon()
	{
		return coupon;
	}

	public void setCoupon(Coupon coupon)
	{
		this.coupon = coupon;
	}

	public Integer getUser_id()
	{
		return user_id;
	}

	public void setUser_id(Integer user_id)
	{
		this.user_id = user_id;
	}

	public Integer getCoupon_id()
	{
		return coupon_id;
	}

	public void setCoupon_id(Integer coupon_id)
	{
		this.coupon_id = coupon_id;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getBegin_at()
	{
		return begin_at;
	}

	public void setBegin_at(Date begin_at)
	{
		this.begin_at = begin_at;
	}

	public Date getEnd_at()
	{
		return end_at;
	}

	public void setEnd_at(Date end_at)
	{
		this.end_at = end_at;
	}

}
