package com.wolaidai.ws.jrocket2.persistence;

// Generated Jan 3, 2015 2:18:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Coupons generated by hbm2java
 */
public class Coupon implements java.io.Serializable
{
	private static final long serialVersionUID = 8009417055399919308L;

	public enum Campaign
	{
		REFERRAL("referral");
		private String m_value;

		private Campaign(String value)
		{
			m_value = value;
		}

		public String getValue()
		{
			return m_value;
		}
	}

	private Integer id;
	private String name;
	private String category;
	private String description;
	private BigDecimal amount;
	private Date beginAt;
	private Date endAt;
	private Date createdAt;
	private Date updatedAt;
	private String campaign;

	public Coupon()
	{}

	public Coupon(Integer id)
	{
		this.id = id;
	}

	public Coupon(Integer id, String name, String category, String description, BigDecimal amount, Date beginAt,
			Date endAt, Date createdAt, Date updatedAt, String campaign)
	{
		this.id = id;
		this.name = name;
		this.category = category;
		this.description = description;
		this.amount = amount;
		this.beginAt = beginAt;
		this.endAt = endAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.campaign = campaign;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getCategory()
	{
		return this.category;
	}

	public void setCategory(String category)
	{
		this.category = category;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public BigDecimal getAmount()
	{
		return this.amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public Date getBeginAt()
	{
		return this.beginAt;
	}

	public void setBeginAt(Date beginAt)
	{
		this.beginAt = beginAt;
	}

	public Date getEndAt()
	{
		return this.endAt;
	}

	public void setEndAt(Date endAt)
	{
		this.endAt = endAt;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public String getCampaign()
	{
		return this.campaign;
	}

	public void setCampaign(String campaign)
	{
		this.campaign = campaign;
	}

}
