package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DelayedJobs generated by hbm2java
 */
public class DelayedJobs implements java.io.Serializable
{

	private int id;
	private int priority;
	private int attempts;
	private String handler;
	private String lastError;
	private Date runAt;
	private Date lockedAt;
	private Date failedAt;
	private String lockedBy;
	private String queue;
	private Date createdAt;
	private Date updatedAt;

	public DelayedJobs()
	{}

	public DelayedJobs(int id, int priority, int attempts, String handler)
	{
		this.id = id;
		this.priority = priority;
		this.attempts = attempts;
		this.handler = handler;
	}

	public DelayedJobs(int id, int priority, int attempts, String handler, String lastError, Date runAt, Date lockedAt,
			Date failedAt, String lockedBy, String queue, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.priority = priority;
		this.attempts = attempts;
		this.handler = handler;
		this.lastError = lastError;
		this.runAt = runAt;
		this.lockedAt = lockedAt;
		this.failedAt = failedAt;
		this.lockedBy = lockedBy;
		this.queue = queue;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public int getPriority()
	{
		return this.priority;
	}

	public void setPriority(int priority)
	{
		this.priority = priority;
	}

	public int getAttempts()
	{
		return this.attempts;
	}

	public void setAttempts(int attempts)
	{
		this.attempts = attempts;
	}

	public String getHandler()
	{
		return this.handler;
	}

	public void setHandler(String handler)
	{
		this.handler = handler;
	}

	public String getLastError()
	{
		return this.lastError;
	}

	public void setLastError(String lastError)
	{
		this.lastError = lastError;
	}

	public Date getRunAt()
	{
		return this.runAt;
	}

	public void setRunAt(Date runAt)
	{
		this.runAt = runAt;
	}

	public Date getLockedAt()
	{
		return this.lockedAt;
	}

	public void setLockedAt(Date lockedAt)
	{
		this.lockedAt = lockedAt;
	}

	public Date getFailedAt()
	{
		return this.failedAt;
	}

	public void setFailedAt(Date failedAt)
	{
		this.failedAt = failedAt;
	}

	public String getLockedBy()
	{
		return this.lockedBy;
	}

	public void setLockedBy(String lockedBy)
	{
		this.lockedBy = lockedBy;
	}

	public String getQueue()
	{
		return this.queue;
	}

	public void setQueue(String queue)
	{
		this.queue = queue;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
