package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.validation.constraints.NotNull;

/**
 * DeviceInfos generated by hbm2java
 */
public class DeviceInfo implements java.io.Serializable
{

	private static final long serialVersionUID = -5558624102815956081L;
	private int id;
	private String model;
	private String os_version;
	private String uuid;
	private String gps;
	private Integer contact_count;
	private String ip;
	private String mac;
	private Integer loan_application_id;
	private Date created_at;
	private Date updated_at;
	
	@NotNull
	private Integer source_id;

	public DeviceInfo()
	{}

	public DeviceInfo(int id)
	{
		this.id = id;
	}

	public DeviceInfo(int id, String model, String os_version, String uuid, String gps, Integer contact_count,
			String ip, String mac, Integer loan_application_id, Date created_at, Date updated_at, Integer source_id)
	{
		this.id = id;
		this.model = model;
		this.os_version = os_version;
		this.uuid = uuid;
		this.gps = gps;
		this.contact_count = contact_count;
		this.ip = ip;
		this.mac = mac;
		this.loan_application_id = loan_application_id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.source_id = source_id;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getModel()
	{
		return this.model;
	}

	public void setModel(String model)
	{
		this.model = model;
	}

	public String getUuid()
	{
		return this.uuid;
	}

	public void setUuid(String uuid)
	{
		this.uuid = uuid;
	}

	public String getGps()
	{
		return this.gps;
	}

	public void setGps(String gps)
	{
		this.gps = gps;
	}

	public String getIp()
	{
		return this.ip;
	}

	public void setIp(String ip)
	{
		this.ip = ip;
	}

	public String getMac()
	{
		return this.mac;
	}

	public void setMac(String mac)
	{
		this.mac = mac;
	}

	public String getOs_version()
	{
		return os_version;
	}

	public void setOs_version(String os_version)
	{
		this.os_version = os_version;
	}

	public Integer getContact_count()
	{
		return contact_count;
	}

	public void setContact_count(Integer contact_count)
	{
		this.contact_count = contact_count;
	}

	public Integer getLoan_application_id()
	{
		return loan_application_id;
	}

	public void setLoan_application_id(Integer loan_application_id)
	{
		this.loan_application_id = loan_application_id;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

	public Integer getSource_id()
	{
		return source_id;
	}

	public void setSource_id(Integer source_id)
	{
		this.source_id = source_id;
	}

}
