package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Documents generated by hbm2java
 */
public class Document implements java.io.Serializable
{

	private static final long serialVersionUID = 8917628361079916628L;
	private Integer id;
	private Integer documentableId;
	private String documentableType;
	private String doc_type;
	private String resource_file_name;
	private String resourceContentType;
	private Integer resourceFileSize;
	private Date resourceUpdatedAt;
	private Date createdAt;
	private Date updatedAt;
	private String access_token;
	//
	private String url;

	public Document()
	{}

	public Document(Integer id)
	{
		this.id = id;
	}

	public Document(int id, Integer documentableId, String documentableType, String docType, String resourceFileName,
			String resourceContentType, Integer resourceFileSize, Date resourceUpdatedAt, Date createdAt,
			Date updatedAt, String accessToken)
	{
		this.id = id;
		this.documentableId = documentableId;
		this.documentableType = documentableType;
		this.doc_type = docType;
		this.resource_file_name = resourceFileName;
		this.resourceContentType = resourceContentType;
		this.resourceFileSize = resourceFileSize;
		this.resourceUpdatedAt = resourceUpdatedAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.access_token = accessToken;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getDocumentableId()
	{
		return this.documentableId;
	}

	public void setDocumentableId(Integer documentableId)
	{
		this.documentableId = documentableId;
	}

	public String getDocumentableType()
	{
		return this.documentableType;
	}

	public void setDocumentableType(String documentableType)
	{
		this.documentableType = documentableType;
	}

	public String getDoc_type()
	{
		return doc_type;
	}

	public void setDoc_type(String doc_type)
	{
		this.doc_type = doc_type;
	}

	public String getResourceContentType()
	{
		return this.resourceContentType;
	}

	public void setResourceContentType(String resourceContentType)
	{
		this.resourceContentType = resourceContentType;
	}

	public Integer getResourceFileSize()
	{
		return this.resourceFileSize;
	}

	public void setResourceFileSize(Integer resourceFileSize)
	{
		this.resourceFileSize = resourceFileSize;
	}

	public Date getResourceUpdatedAt()
	{
		return this.resourceUpdatedAt;
	}

	public void setResourceUpdatedAt(Date resourceUpdatedAt)
	{
		this.resourceUpdatedAt = resourceUpdatedAt;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public String getResource_file_name()
	{
		return resource_file_name;
	}

	public void setResource_file_name(String resource_file_name)
	{
		this.resource_file_name = resource_file_name;
	}

	public String getAccess_token()
	{
		return access_token;
	}

	public void setAccess_token(String access_token)
	{
		this.access_token = access_token;
	}

	public String getUrl()
	{
		return url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

}
