package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * DueSettlements generated by hbm2java
 */
public class DueSettlements implements java.io.Serializable
{

	private int id;
	private Integer accountTransactionId;
	private Integer dueId;
	private BigDecimal amount;
	private Date createdAt;
	private Date updatedAt;

	public DueSettlements()
	{}

	public DueSettlements(int id)
	{
		this.id = id;
	}

	public DueSettlements(int id, Integer accountTransactionId, Integer dueId, BigDecimal amount, Date createdAt,
			Date updatedAt)
	{
		this.id = id;
		this.accountTransactionId = accountTransactionId;
		this.dueId = dueId;
		this.amount = amount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getAccountTransactionId()
	{
		return this.accountTransactionId;
	}

	public void setAccountTransactionId(Integer accountTransactionId)
	{
		this.accountTransactionId = accountTransactionId;
	}

	public Integer getDueId()
	{
		return this.dueId;
	}

	public void setDueId(Integer dueId)
	{
		this.dueId = dueId;
	}

	public BigDecimal getAmount()
	{
		return this.amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
