package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * DueSettlements generated by hbm2java
 */
public class DueSettlement implements java.io.Serializable
{
	private static final long serialVersionUID = 7445629703327864469L;
	private Integer id;
	private Integer account_transaction_id;
	private Integer due_id;
	private BigDecimal amount;
	private Date created_at;
	private Date updated_at;

	public DueSettlement()
	{}

	public DueSettlement(Integer id)
	{
		this.id = id;
	}

	public DueSettlement(Integer id, Integer accountTransactionId, Integer dueId, BigDecimal amount, Date createdAt,
			Date updatedAt)
	{
		this.id = id;
		this.account_transaction_id = accountTransactionId;
		this.due_id = dueId;
		this.amount = amount;
		this.created_at = createdAt;
		this.updated_at = updatedAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public BigDecimal getAmount()
	{
		return this.amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public Integer getAccount_transaction_id()
	{
		return account_transaction_id;
	}

	public void setAccount_transaction_id(Integer account_transaction_id)
	{
		this.account_transaction_id = account_transaction_id;
	}

	public Integer getDue_id()
	{
		return due_id;
	}

	public void setDue_id(Integer due_id)
	{
		this.due_id = due_id;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

}
