package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Dues generated by hbm2java
 */
public class Dues implements java.io.Serializable
{

	private int id;
	private Integer loanId;
	private Integer index;
	private BigDecimal amount;
	private Date dueDate;
	private String dueType;
	private Date createdAt;
	private Date updatedAt;

	public Dues()
	{}

	public Dues(int id)
	{
		this.id = id;
	}

	public Dues(int id, Integer loanId, Integer index, BigDecimal amount, Date dueDate, String dueType, Date createdAt,
			Date updatedAt)
	{
		this.id = id;
		this.loanId = loanId;
		this.index = index;
		this.amount = amount;
		this.dueDate = dueDate;
		this.dueType = dueType;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getLoanId()
	{
		return this.loanId;
	}

	public void setLoanId(Integer loanId)
	{
		this.loanId = loanId;
	}

	public Integer getIndex()
	{
		return this.index;
	}

	public void setIndex(Integer index)
	{
		this.index = index;
	}

	public BigDecimal getAmount()
	{
		return this.amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public Date getDueDate()
	{
		return this.dueDate;
	}

	public void setDueDate(Date dueDate)
	{
		this.dueDate = dueDate;
	}

	public String getDueType()
	{
		return this.dueType;
	}

	public void setDueType(String dueType)
	{
		this.dueType = dueType;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
