package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Educations generated by hbm2java
 */
public class Educations implements java.io.Serializable
{

	private static final long serialVersionUID = 2631787604527711513L;
	private Integer id;
	private Integer userId;
	private Integer loanApplicationId;
	private String school;
	private String department;
	private String major;
	private Integer degree_id;
	private Date enrolled_at;
	private Date graduated_at;
	private Date createdAt;
	private Date updatedAt;
	private Addresses address;

	public Educations()
	{}

	public Educations(Integer id)
	{
		this.id = id;
	}

	public Educations(int id, Integer userId, Integer loanApplicationId, String school, String department,
			String major, Integer degreeId, Date enrolledAt, Date graduatedAt, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.userId = userId;
		this.loanApplicationId = loanApplicationId;
		this.school = school;
		this.department = department;
		this.major = major;
		this.degree_id = degreeId;
		this.enrolled_at = enrolledAt;
		this.graduated_at = graduatedAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public Integer getLoanApplicationId()
	{
		return this.loanApplicationId;
	}

	public void setLoanApplicationId(Integer loanApplicationId)
	{
		this.loanApplicationId = loanApplicationId;
	}

	public String getSchool()
	{
		return this.school;
	}

	public void setSchool(String school)
	{
		this.school = school;
	}

	public String getDepartment()
	{
		return this.department;
	}

	public void setDepartment(String department)
	{
		this.department = department;
	}

	public String getMajor()
	{
		return this.major;
	}

	public void setMajor(String major)
	{
		this.major = major;
	}

	public Integer getDegree_id()
	{
		return degree_id;
	}

	public void setDegree_id(Integer degree_id)
	{
		this.degree_id = degree_id;
	}

	public Date getEnrolled_at()
	{
		return enrolled_at;
	}

	public void setEnrolled_at(Date enrolled_at)
	{
		this.enrolled_at = enrolled_at;
	}

	public Date getGraduated_at()
	{
		return graduated_at;
	}

	public void setGraduated_at(Date graduated_at)
	{
		this.graduated_at = graduated_at;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public Addresses getAddress()
	{
		return address;
	}

	public void setAddress(Addresses address)
	{
		this.address = address;
	}

}
