package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FraudIncidents generated by hbm2java
 */
public class FraudIncidents implements java.io.Serializable
{

	private int id;
	private Integer loanApplicationId;
	private String fraudIncidentType;
	private String refMessage;
	private Boolean ignore;
	private Date createdAt;
	private Date updatedAt;

	public FraudIncidents()
	{}

	public FraudIncidents(int id)
	{
		this.id = id;
	}

	public FraudIncidents(int id, Integer loanApplicationId, String fraudIncidentType, String refMessage,
			Boolean ignore, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.loanApplicationId = loanApplicationId;
		this.fraudIncidentType = fraudIncidentType;
		this.refMessage = refMessage;
		this.ignore = ignore;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getLoanApplicationId()
	{
		return this.loanApplicationId;
	}

	public void setLoanApplicationId(Integer loanApplicationId)
	{
		this.loanApplicationId = loanApplicationId;
	}

	public String getFraudIncidentType()
	{
		return this.fraudIncidentType;
	}

	public void setFraudIncidentType(String fraudIncidentType)
	{
		this.fraudIncidentType = fraudIncidentType;
	}

	public String getRefMessage()
	{
		return this.refMessage;
	}

	public void setRefMessage(String refMessage)
	{
		this.refMessage = refMessage;
	}

	public Boolean getIgnore()
	{
		return this.ignore;
	}

	public void setIgnore(Boolean ignore)
	{
		this.ignore = ignore;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
