package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Geolocations generated by hbm2java
 */
public class Geolocations implements java.io.Serializable
{

	private int id;
	private String geoType;
	private String geoValue;
	private String province;
	private String city;
	private String district;
	private String otherInfo;
	private Date createdAt;
	private Date updatedAt;

	public Geolocations()
	{}

	public Geolocations(int id)
	{
		this.id = id;
	}

	public Geolocations(int id, String geoType, String geoValue, String province, String city, String district,
			String otherInfo, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.geoType = geoType;
		this.geoValue = geoValue;
		this.province = province;
		this.city = city;
		this.district = district;
		this.otherInfo = otherInfo;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getGeoType()
	{
		return this.geoType;
	}

	public void setGeoType(String geoType)
	{
		this.geoType = geoType;
	}

	public String getGeoValue()
	{
		return this.geoValue;
	}

	public void setGeoValue(String geoValue)
	{
		this.geoValue = geoValue;
	}

	public String getProvince()
	{
		return this.province;
	}

	public void setProvince(String province)
	{
		this.province = province;
	}

	public String getCity()
	{
		return this.city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	public String getDistrict()
	{
		return this.district;
	}

	public void setDistrict(String district)
	{
		this.district = district;
	}

	public String getOtherInfo()
	{
		return this.otherInfo;
	}

	public void setOtherInfo(String otherInfo)
	{
		this.otherInfo = otherInfo;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
