package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Lenders generated by hbm2java
 */
public class Lenders implements java.io.Serializable
{

	private int id;
	private String mobile;
	private String encryptedPassword;
	private String resetPasswordToken;
	private Date resetPasswordSentAt;
	private int signInCount;
	private Date currentSignInAt;
	private Date lastSignInAt;
	private String currentSignInIp;
	private String lastSignInIp;
	private int failedAttempts;
	private String unlockToken;
	private Date lockedAt;
	private String email;
	private Date createdAt;
	private Date updatedAt;

	public Lenders()
	{}

	public Lenders(int id, String mobile, String encryptedPassword, int signInCount, int failedAttempts)
	{
		this.id = id;
		this.mobile = mobile;
		this.encryptedPassword = encryptedPassword;
		this.signInCount = signInCount;
		this.failedAttempts = failedAttempts;
	}

	public Lenders(int id, String mobile, String encryptedPassword, String resetPasswordToken,
			Date resetPasswordSentAt, int signInCount, Date currentSignInAt, Date lastSignInAt, String currentSignInIp,
			String lastSignInIp, int failedAttempts, String unlockToken, Date lockedAt, String email, Date createdAt,
			Date updatedAt)
	{
		this.id = id;
		this.mobile = mobile;
		this.encryptedPassword = encryptedPassword;
		this.resetPasswordToken = resetPasswordToken;
		this.resetPasswordSentAt = resetPasswordSentAt;
		this.signInCount = signInCount;
		this.currentSignInAt = currentSignInAt;
		this.lastSignInAt = lastSignInAt;
		this.currentSignInIp = currentSignInIp;
		this.lastSignInIp = lastSignInIp;
		this.failedAttempts = failedAttempts;
		this.unlockToken = unlockToken;
		this.lockedAt = lockedAt;
		this.email = email;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getEncryptedPassword()
	{
		return this.encryptedPassword;
	}

	public void setEncryptedPassword(String encryptedPassword)
	{
		this.encryptedPassword = encryptedPassword;
	}

	public String getResetPasswordToken()
	{
		return this.resetPasswordToken;
	}

	public void setResetPasswordToken(String resetPasswordToken)
	{
		this.resetPasswordToken = resetPasswordToken;
	}

	public Date getResetPasswordSentAt()
	{
		return this.resetPasswordSentAt;
	}

	public void setResetPasswordSentAt(Date resetPasswordSentAt)
	{
		this.resetPasswordSentAt = resetPasswordSentAt;
	}

	public int getSignInCount()
	{
		return this.signInCount;
	}

	public void setSignInCount(int signInCount)
	{
		this.signInCount = signInCount;
	}

	public Date getCurrentSignInAt()
	{
		return this.currentSignInAt;
	}

	public void setCurrentSignInAt(Date currentSignInAt)
	{
		this.currentSignInAt = currentSignInAt;
	}

	public Date getLastSignInAt()
	{
		return this.lastSignInAt;
	}

	public void setLastSignInAt(Date lastSignInAt)
	{
		this.lastSignInAt = lastSignInAt;
	}

	public String getCurrentSignInIp()
	{
		return this.currentSignInIp;
	}

	public void setCurrentSignInIp(String currentSignInIp)
	{
		this.currentSignInIp = currentSignInIp;
	}

	public String getLastSignInIp()
	{
		return this.lastSignInIp;
	}

	public void setLastSignInIp(String lastSignInIp)
	{
		this.lastSignInIp = lastSignInIp;
	}

	public int getFailedAttempts()
	{
		return this.failedAttempts;
	}

	public void setFailedAttempts(int failedAttempts)
	{
		this.failedAttempts = failedAttempts;
	}

	public String getUnlockToken()
	{
		return this.unlockToken;
	}

	public void setUnlockToken(String unlockToken)
	{
		this.unlockToken = unlockToken;
	}

	public Date getLockedAt()
	{
		return this.lockedAt;
	}

	public void setLockedAt(Date lockedAt)
	{
		this.lockedAt = lockedAt;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
