package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LenderProfiles generated by hbm2java
 */
public class LenderProfiles implements java.io.Serializable
{

	private int id;
	private String name;
	private String cnid;
	private String address;
	private String bankAccount;
	private Integer investmentAmount;
	private Integer lenderId;
	private Date createdAt;
	private Date updatedAt;
	private Integer bankId;
	private Integer bankProvinceId;
	private Integer bankCityId;

	public LenderProfiles()
	{}

	public LenderProfiles(int id)
	{
		this.id = id;
	}

	public LenderProfiles(int id, String name, String cnid, String address, String bankAccount,
			Integer investmentAmount, Integer lenderId, Date createdAt, Date updatedAt, Integer bankId,
			Integer bankProvinceId, Integer bankCityId)
	{
		this.id = id;
		this.name = name;
		this.cnid = cnid;
		this.address = address;
		this.bankAccount = bankAccount;
		this.investmentAmount = investmentAmount;
		this.lenderId = lenderId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.bankId = bankId;
		this.bankProvinceId = bankProvinceId;
		this.bankCityId = bankCityId;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getCnid()
	{
		return this.cnid;
	}

	public void setCnid(String cnid)
	{
		this.cnid = cnid;
	}

	public String getAddress()
	{
		return this.address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	public String getBankAccount()
	{
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount)
	{
		this.bankAccount = bankAccount;
	}

	public Integer getInvestmentAmount()
	{
		return this.investmentAmount;
	}

	public void setInvestmentAmount(Integer investmentAmount)
	{
		this.investmentAmount = investmentAmount;
	}

	public Integer getLenderId()
	{
		return this.lenderId;
	}

	public void setLenderId(Integer lenderId)
	{
		this.lenderId = lenderId;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public Integer getBankId()
	{
		return this.bankId;
	}

	public void setBankId(Integer bankId)
	{
		this.bankId = bankId;
	}

	public Integer getBankProvinceId()
	{
		return this.bankProvinceId;
	}

	public void setBankProvinceId(Integer bankProvinceId)
	{
		this.bankProvinceId = bankProvinceId;
	}

	public Integer getBankCityId()
	{
		return this.bankCityId;
	}

	public void setBankCityId(Integer bankCityId)
	{
		this.bankCityId = bankCityId;
	}

}
