package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * Liaisons generated by hbm2java
 */
public class Liaison implements java.io.Serializable
{

	private static final long serialVersionUID = -3639781565641502687L;
	private Integer id;
	private Integer userId;
	private String name;
	private String relationship;
	private String mobile;
	private String comments;
	private String company;
	private String position;
	private Integer sourceId;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private List<Addresses> addresses;
	//
	private Addresses resident_address;
	private Addresses company_address;

	public Liaison()
	{}

	public Liaison(Integer id)
	{
		this.id = id;
	}

	public Liaison(int id, Integer userId, String name, String relationship, String mobile, String comments,
			String company, String position, Integer sourceId, Date createdAt, Date updatedAt, Date deletedAt)
	{
		this.id = id;
		this.userId = userId;
		this.name = name;
		this.relationship = relationship;
		this.mobile = mobile;
		this.comments = comments;
		this.company = company;
		this.position = position;
		this.sourceId = sourceId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getRelationship()
	{
		return this.relationship;
	}

	public void setRelationship(String relationship)
	{
		this.relationship = relationship;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getComments()
	{
		return this.comments;
	}

	public void setComments(String comments)
	{
		this.comments = comments;
	}

	public String getCompany()
	{
		return this.company;
	}

	public void setCompany(String company)
	{
		this.company = company;
	}

	public String getPosition()
	{
		return this.position;
	}

	public void setPosition(String position)
	{
		this.position = position;
	}

	public Integer getSourceId()
	{
		return this.sourceId;
	}

	public void setSourceId(Integer sourceId)
	{
		this.sourceId = sourceId;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public Date getDeletedAt()
	{
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt)
	{
		this.deletedAt = deletedAt;
	}

	public List<Addresses> getAddresses()
	{
		return addresses;
	}

	public void setAddresses(List<Addresses> addresses)
	{
		this.addresses = addresses;
	}

	public Addresses getResident_address()
	{
		return resident_address;
	}

	public void setResident_address(Addresses resident_address)
	{
		this.resident_address = resident_address;
	}

	public Addresses getCompany_address()
	{
		return company_address;
	}

	public void setCompany_address(Addresses company_address)
	{
		this.company_address = company_address;
	}

}
