package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanDiscounts generated by hbm2java
 */
public class LoanDiscounts implements java.io.Serializable
{

	private int id;
	private Integer loanId;
	private Integer discountId;
	private BigDecimal amount;
	private Date createdAt;
	private Date updatedAt;

	public LoanDiscounts()
	{}

	public LoanDiscounts(int id)
	{
		this.id = id;
	}

	public LoanDiscounts(int id, Integer loanId, Integer discountId, BigDecimal amount, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.loanId = loanId;
		this.discountId = discountId;
		this.amount = amount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getLoanId()
	{
		return this.loanId;
	}

	public void setLoanId(Integer loanId)
	{
		this.loanId = loanId;
	}

	public Integer getDiscountId()
	{
		return this.discountId;
	}

	public void setDiscountId(Integer discountId)
	{
		this.discountId = discountId;
	}

	public BigDecimal getAmount()
	{
		return this.amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
