package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanApplications generated by hbm2java
 */
public class LoanApplication implements java.io.Serializable
{

	private static final long serialVersionUID = 4184326655026343181L;
	private Integer id;
	private Integer borrower_id;
	private String tenor;
	private Integer amount;
	private String state;
	private Integer position_id;
	private Date created_at;
	private Date updated_at;
	private String application_id;
	private Integer residence_district_id;
	private String residence_street;
	private String geolocation_json;
	private BigDecimal handling_fee;
	private BigDecimal interest_rate;
	private BigDecimal management_fee_rate;
	private BigDecimal withdrawal_fee_rate;
	private Integer bank_id;
	private String account_number;
	private Date applied_at;
	private Date approved_at;
	private String purpose;
	private BigDecimal deposit_fee_rate;
	private Integer aip_by_id;
	private Integer bank_city_id;
	private String reason_code1;
	private String reason_code2;
	private String reason_code3;
	private String reject_code;
	private Integer picked_up_by_id;
	private String fm_score;
	private Integer bank_card_id;
	private Integer applied_amount;
	private String applied_tenor;
	private Date push_backed_at;
	private Date confirmed_at;
	private String origin;
	//
	private DeviceInfo m_device_info;

	public LoanApplication()
	{}

	public LoanApplication(Integer id)
	{
		this.id = id;
	}

	public LoanApplication(Integer id, Integer borrower_id, String tenor, Integer amount, String state,
			Integer position_id, Date created_at, Date updated_at, String application_id,
			Integer residence_district_id, String residence_street, String geolocation_json, BigDecimal handling_fee,
			BigDecimal interest_rate, BigDecimal management_fee_rate, BigDecimal withdrawal_fee_rate, Integer bank_id,
			String account_number, Date applied_at, Date approved_at, String purpose, BigDecimal deposit_fee_rate,
			Integer aip_by_id, Integer bank_city_id, String reason_code1, String reason_code2, String reason_code3,
			String reject_code, Integer picked_up_by_id, String fm_score, Integer bank_card_id, Integer applied_amount,
			String applied_tenor, Date push_backed_at, Date confirmed_at, String origin)
	{
		this.id = id;
		this.borrower_id = borrower_id;
		this.tenor = tenor;
		this.amount = amount;
		this.state = state;
		this.position_id = position_id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.application_id = application_id;
		this.residence_district_id = residence_district_id;
		this.residence_street = residence_street;
		this.geolocation_json = geolocation_json;
		this.handling_fee = handling_fee;
		this.interest_rate = interest_rate;
		this.management_fee_rate = management_fee_rate;
		this.withdrawal_fee_rate = withdrawal_fee_rate;
		this.bank_id = bank_id;
		this.account_number = account_number;
		this.applied_at = applied_at;
		this.approved_at = approved_at;
		this.purpose = purpose;
		this.deposit_fee_rate = deposit_fee_rate;
		this.aip_by_id = aip_by_id;
		this.bank_city_id = bank_city_id;
		this.reason_code1 = reason_code1;
		this.reason_code2 = reason_code2;
		this.reason_code3 = reason_code3;
		this.reject_code = reject_code;
		this.picked_up_by_id = picked_up_by_id;
		this.fm_score = fm_score;
		this.bank_card_id = bank_card_id;
		this.applied_amount = applied_amount;
		this.applied_tenor = applied_tenor;
		this.push_backed_at = push_backed_at;
		this.confirmed_at = confirmed_at;
		this.origin = origin;
	}

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getBorrower_id()
	{
		return borrower_id;
	}

	public void setBorrower_id(Integer borrower_id)
	{
		this.borrower_id = borrower_id;
	}

	public String getTenor()
	{
		return tenor;
	}

	public void setTenor(String tenor)
	{
		this.tenor = tenor;
	}

	public Integer getAmount()
	{
		return amount;
	}

	public void setAmount(Integer amount)
	{
		this.amount = amount;
	}

	public String getState()
	{
		return state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	public Integer getPosition_id()
	{
		return position_id;
	}

	public void setPosition_id(Integer position_id)
	{
		this.position_id = position_id;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

	public String getApplication_id()
	{
		return application_id;
	}

	public void setApplication_id(String application_id)
	{
		this.application_id = application_id;
	}

	public Integer getResidence_district_id()
	{
		return residence_district_id;
	}

	public void setResidence_district_id(Integer residence_district_id)
	{
		this.residence_district_id = residence_district_id;
	}

	public String getResidence_street()
	{
		return residence_street;
	}

	public void setResidence_street(String residence_street)
	{
		this.residence_street = residence_street;
	}

	public String getGeolocation_json()
	{
		return geolocation_json;
	}

	public void setGeolocation_json(String geolocation_json)
	{
		this.geolocation_json = geolocation_json;
	}

	public BigDecimal getHandling_fee()
	{
		return handling_fee;
	}

	public void setHandling_fee(BigDecimal handling_fee)
	{
		this.handling_fee = handling_fee;
	}

	public BigDecimal getInterest_rate()
	{
		return interest_rate;
	}

	public void setInterest_rate(BigDecimal interest_rate)
	{
		this.interest_rate = interest_rate;
	}

	public BigDecimal getManagement_fee_rate()
	{
		return management_fee_rate;
	}

	public void setManagement_fee_rate(BigDecimal management_fee_rate)
	{
		this.management_fee_rate = management_fee_rate;
	}

	public BigDecimal getWithdrawal_fee_rate()
	{
		return withdrawal_fee_rate;
	}

	public void setWithdrawal_fee_rate(BigDecimal withdrawal_fee_rate)
	{
		this.withdrawal_fee_rate = withdrawal_fee_rate;
	}

	public Integer getBank_id()
	{
		return bank_id;
	}

	public void setBank_id(Integer bank_id)
	{
		this.bank_id = bank_id;
	}

	public String getAccount_number()
	{
		return account_number;
	}

	public void setAccount_number(String account_number)
	{
		this.account_number = account_number;
	}

	public Date getApplied_at()
	{
		return applied_at;
	}

	public void setApplied_at(Date applied_at)
	{
		this.applied_at = applied_at;
	}

	public Date getApproved_at()
	{
		return approved_at;
	}

	public void setApproved_at(Date approved_at)
	{
		this.approved_at = approved_at;
	}

	public String getPurpose()
	{
		return purpose;
	}

	public void setPurpose(String purpose)
	{
		this.purpose = purpose;
	}

	public BigDecimal getDeposit_fee_rate()
	{
		return deposit_fee_rate;
	}

	public void setDeposit_fee_rate(BigDecimal deposit_fee_rate)
	{
		this.deposit_fee_rate = deposit_fee_rate;
	}

	public Integer getAip_by_id()
	{
		return aip_by_id;
	}

	public void setAip_by_id(Integer aip_by_id)
	{
		this.aip_by_id = aip_by_id;
	}

	public Integer getBank_city_id()
	{
		return bank_city_id;
	}

	public void setBank_city_id(Integer bank_city_id)
	{
		this.bank_city_id = bank_city_id;
	}

	public String getReason_code1()
	{
		return reason_code1;
	}

	public void setReason_code1(String reason_code1)
	{
		this.reason_code1 = reason_code1;
	}

	public String getReason_code2()
	{
		return reason_code2;
	}

	public void setReason_code2(String reason_code2)
	{
		this.reason_code2 = reason_code2;
	}

	public String getReason_code3()
	{
		return reason_code3;
	}

	public void setReason_code3(String reason_code3)
	{
		this.reason_code3 = reason_code3;
	}

	public String getReject_code()
	{
		return reject_code;
	}

	public void setReject_code(String reject_code)
	{
		this.reject_code = reject_code;
	}

	public Integer getPicked_up_by_id()
	{
		return picked_up_by_id;
	}

	public void setPicked_up_by_id(Integer picked_up_by_id)
	{
		this.picked_up_by_id = picked_up_by_id;
	}

	public String getFm_score()
	{
		return fm_score;
	}

	public void setFm_score(String fm_score)
	{
		this.fm_score = fm_score;
	}

	public Integer getBank_card_id()
	{
		return bank_card_id;
	}

	public void setBank_card_id(Integer bank_card_id)
	{
		this.bank_card_id = bank_card_id;
	}

	public Integer getApplied_amount()
	{
		return applied_amount;
	}

	public void setApplied_amount(Integer applied_amount)
	{
		this.applied_amount = applied_amount;
	}

	public String getApplied_tenor()
	{
		return applied_tenor;
	}

	public void setApplied_tenor(String applied_tenor)
	{
		this.applied_tenor = applied_tenor;
	}

	public Date getPush_backed_at()
	{
		return push_backed_at;
	}

	public void setPush_backed_at(Date push_backed_at)
	{
		this.push_backed_at = push_backed_at;
	}

	public Date getConfirmed_at()
	{
		return confirmed_at;
	}

	public void setConfirmed_at(Date confirmed_at)
	{
		this.confirmed_at = confirmed_at;
	}

	public String getOrigin()
	{
		return origin;
	}

	public void setOrigin(String origin)
	{
		this.origin = origin;
	}

	public DeviceInfo getDevice_info()
	{
		return m_device_info;
	}

	public void setDevice_info(DeviceInfo device_info)
	{
		m_device_info = device_info;
	}

	
}
