package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanApplications generated by hbm2java
 */
public class LoanApplications implements java.io.Serializable
{

	private static final long serialVersionUID = 4184326655026343181L;
	private Integer id;
	private Integer borrowerId;
	private String tenor;
	private Integer amount;
	private String state;
	private Integer positionId;
	private Date createdAt;
	private Date updatedAt;
	private String applicationId;
	private Integer residenceDistrictId;
	private String residenceStreet;
	private String geolocationJson;
	private BigDecimal handlingFee;
	private BigDecimal interestRate;
	private BigDecimal managementFeeRate;
	private BigDecimal withdrawalFeeRate;
	private Integer bankId;
	private String accountNumber;
	private Date appliedAt;
	private Date approvedAt;
	private String purpose;
	private BigDecimal depositFeeRate;
	private Integer aipById;
	private Integer bankCityId;
	private String reasonCode1;
	private String reasonCode2;
	private String reasonCode3;
	private String rejectCode;
	private Integer pickedUpById;
	private String fmScore;
	private Integer bankCardId;
	private Integer appliedAmount;
	private String appliedTenor;
	private Date pushBackedAt;
	private Date confirmedAt;
	//
	private String m_repayment_method;
	private String m_reject_description;
	private DeviceInfos m_device_info;

	public LoanApplications()
	{}

	public LoanApplications(Integer id)
	{
		this.id = id;
	}

	public LoanApplications(Integer id, Integer borrowerId, String tenor, Integer amount, String state, Integer positionId,
			Date createdAt, Date updatedAt, String applicationId, Integer residenceDistrictId, String residenceStreet,
			String geolocationJson, BigDecimal handlingFee, BigDecimal interestRate, BigDecimal managementFeeRate,
			BigDecimal withdrawalFeeRate, Integer bankId, String accountNumber, Date appliedAt, Date approvedAt,
			String purpose, BigDecimal depositFeeRate, Integer aipById, Integer bankCityId, String reasonCode1,
			String reasonCode2, String reasonCode3, String rejectCode, Integer pickedUpById, String fmScore,
			Integer bankCardId, Integer appliedAmount, String appliedTenor, Date pushBackedAt, Date confirmedAt)
	{
		this.id = id;
		this.borrowerId = borrowerId;
		this.tenor = tenor;
		this.amount = amount;
		this.state = state;
		this.positionId = positionId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.applicationId = applicationId;
		this.residenceDistrictId = residenceDistrictId;
		this.residenceStreet = residenceStreet;
		this.geolocationJson = geolocationJson;
		this.handlingFee = handlingFee;
		this.interestRate = interestRate;
		this.managementFeeRate = managementFeeRate;
		this.withdrawalFeeRate = withdrawalFeeRate;
		this.bankId = bankId;
		this.accountNumber = accountNumber;
		this.appliedAt = appliedAt;
		this.approvedAt = approvedAt;
		this.purpose = purpose;
		this.depositFeeRate = depositFeeRate;
		this.aipById = aipById;
		this.bankCityId = bankCityId;
		this.reasonCode1 = reasonCode1;
		this.reasonCode2 = reasonCode2;
		this.reasonCode3 = reasonCode3;
		this.rejectCode = rejectCode;
		this.pickedUpById = pickedUpById;
		this.fmScore = fmScore;
		this.bankCardId = bankCardId;
		this.appliedAmount = appliedAmount;
		this.appliedTenor = appliedTenor;
		this.pushBackedAt = pushBackedAt;
		this.confirmedAt = confirmedAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getBorrowerId()
	{
		return this.borrowerId;
	}

	public void setBorrowerId(Integer borrowerId)
	{
		this.borrowerId = borrowerId;
	}

	public String getTenor()
	{
		return this.tenor;
	}

	public void setTenor(String tenor)
	{
		this.tenor = tenor;
	}

	public Integer getAmount()
	{
		return this.amount;
	}

	public void setAmount(Integer amount)
	{
		this.amount = amount;
	}

	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	public Integer getPositionId()
	{
		return this.positionId;
	}

	public void setPositionId(Integer positionId)
	{
		this.positionId = positionId;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public String getApplicationId()
	{
		return this.applicationId;
	}

	public void setApplicationId(String applicationId)
	{
		this.applicationId = applicationId;
	}

	public Integer getResidenceDistrictId()
	{
		return this.residenceDistrictId;
	}

	public void setResidenceDistrictId(Integer residenceDistrictId)
	{
		this.residenceDistrictId = residenceDistrictId;
	}

	public String getResidenceStreet()
	{
		return this.residenceStreet;
	}

	public void setResidenceStreet(String residenceStreet)
	{
		this.residenceStreet = residenceStreet;
	}

	public String getGeolocationJson()
	{
		return this.geolocationJson;
	}

	public void setGeolocationJson(String geolocationJson)
	{
		this.geolocationJson = geolocationJson;
	}

	public BigDecimal getHandlingFee()
	{
		return this.handlingFee;
	}

	public void setHandlingFee(BigDecimal handlingFee)
	{
		this.handlingFee = handlingFee;
	}

	public BigDecimal getInterestRate()
	{
		return this.interestRate;
	}

	public void setInterestRate(BigDecimal interestRate)
	{
		this.interestRate = interestRate;
	}

	public BigDecimal getManagementFeeRate()
	{
		return this.managementFeeRate;
	}

	public void setManagementFeeRate(BigDecimal managementFeeRate)
	{
		this.managementFeeRate = managementFeeRate;
	}

	public BigDecimal getWithdrawalFeeRate()
	{
		return this.withdrawalFeeRate;
	}

	public void setWithdrawalFeeRate(BigDecimal withdrawalFeeRate)
	{
		this.withdrawalFeeRate = withdrawalFeeRate;
	}

	public Integer getBankId()
	{
		return this.bankId;
	}

	public void setBankId(Integer bankId)
	{
		this.bankId = bankId;
	}

	public String getAccountNumber()
	{
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber)
	{
		this.accountNumber = accountNumber;
	}

	public Date getAppliedAt()
	{
		return this.appliedAt;
	}

	public void setAppliedAt(Date appliedAt)
	{
		this.appliedAt = appliedAt;
	}

	public Date getApprovedAt()
	{
		return this.approvedAt;
	}

	public void setApprovedAt(Date approvedAt)
	{
		this.approvedAt = approvedAt;
	}

	public String getPurpose()
	{
		return this.purpose;
	}

	public void setPurpose(String purpose)
	{
		this.purpose = purpose;
	}

	public BigDecimal getDepositFeeRate()
	{
		return this.depositFeeRate;
	}

	public void setDepositFeeRate(BigDecimal depositFeeRate)
	{
		this.depositFeeRate = depositFeeRate;
	}

	public Integer getAipById()
	{
		return this.aipById;
	}

	public void setAipById(Integer aipById)
	{
		this.aipById = aipById;
	}

	public Integer getBankCityId()
	{
		return this.bankCityId;
	}

	public void setBankCityId(Integer bankCityId)
	{
		this.bankCityId = bankCityId;
	}

	public String getReasonCode1()
	{
		return this.reasonCode1;
	}

	public void setReasonCode1(String reasonCode1)
	{
		this.reasonCode1 = reasonCode1;
	}

	public String getReasonCode2()
	{
		return this.reasonCode2;
	}

	public void setReasonCode2(String reasonCode2)
	{
		this.reasonCode2 = reasonCode2;
	}

	public String getReasonCode3()
	{
		return this.reasonCode3;
	}

	public void setReasonCode3(String reasonCode3)
	{
		this.reasonCode3 = reasonCode3;
	}

	public String getRejectCode()
	{
		return this.rejectCode;
	}

	public void setRejectCode(String rejectCode)
	{
		this.rejectCode = rejectCode;
	}

	public Integer getPickedUpById()
	{
		return this.pickedUpById;
	}

	public void setPickedUpById(Integer pickedUpById)
	{
		this.pickedUpById = pickedUpById;
	}

	public String getFmScore()
	{
		return this.fmScore;
	}

	public void setFmScore(String fmScore)
	{
		this.fmScore = fmScore;
	}

	public Integer getBankCardId()
	{
		return this.bankCardId;
	}

	public void setBankCardId(Integer bankCardId)
	{
		this.bankCardId = bankCardId;
	}

	public Integer getAppliedAmount()
	{
		return this.appliedAmount;
	}

	public void setAppliedAmount(Integer appliedAmount)
	{
		this.appliedAmount = appliedAmount;
	}

	public String getAppliedTenor()
	{
		return this.appliedTenor;
	}

	public void setAppliedTenor(String appliedTenor)
	{
		this.appliedTenor = appliedTenor;
	}

	public Date getPushBackedAt()
	{
		return this.pushBackedAt;
	}

	public void setPushBackedAt(Date pushBackedAt)
	{
		this.pushBackedAt = pushBackedAt;
	}

	public Date getConfirmedAt()
	{
		return this.confirmedAt;
	}

	public void setConfirmedAt(Date confirmedAt)
	{
		this.confirmedAt = confirmedAt;
	}

	public String getRepayment_method()
	{
		return m_repayment_method;
	}

	public void setRepayment_method(String repayment_method)
	{
		m_repayment_method = repayment_method;
	}

	public String getReject_description()
	{
		return m_reject_description;
	}

	public void setReject_description(String reject_description)
	{
		m_reject_description = reject_description;
	}

	public DeviceInfos getDevice_info()
	{
		return m_device_info;
	}

	public void setDevice_info(DeviceInfos device_info)
	{
		m_device_info = device_info;
	}

}
