package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Loans generated by hbm2java
 */
public class Loan implements java.io.Serializable
{
	private static final long serialVersionUID = 2024397452930519440L;
	private Integer id;
	private Integer loan_application_id;
	private String state;
	private Date disbursed_at;
	private Date created_at;
	private Date updated_at;
	private Integer borrower_id;
	private String application_id;
	private BigDecimal overdue_penalty;
	private BigDecimal overdue_management_fee_rate;
	private BigDecimal overdue_interest_rate;
	private Date expected_repayment_date;
	private Integer lender_id;
	private Date closed_at;
	private Date last_payment_run_at;
	private Date last_past_due_at;
	private String tenor;
	private BigDecimal amount;
	private Boolean verified_bank_card;
	private Integer overdue_charge_version;
	private LoanApplication loanApplication;
	private List<Due> dues;

	public enum State
	{
		FUNDED("funded"),
		DISBURSED("disbursed"),
		DISBURSE_FAILED("disburse_failed"),
		REPAIED("repaied"),
		ERALY_SETTLED("early_settled"),
		CLOSED("closed");

		private String m_value;

		private State(String value)
		{
			m_value = value;
		}

		public String getValue()
		{
			return m_value;
		}
	}

	public Loan()
	{}

	public Loan(Integer id)
	{
		this.id = id;
	}

	public Loan(Integer id, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.created_at = createdAt;
		this.updated_at = updatedAt;
	}

	public Loan(Integer id, Integer loanApplicationId, String state, Date disbursedAt, Date createdAt, Date updatedAt,
			Integer borrowerId, String applicationId, BigDecimal overduePenalty, BigDecimal overdueManagementFeeRate,
			BigDecimal overdueInterestRate, Date expectedRepaymentDate, Integer lenderId, Date closedAt,
			Date lastPaymentRunAt, Date lastPastDueAt, String tenor, BigDecimal amount, Boolean verifiedBankCard,
			Integer overdueChargeVersion)
	{
		this.id = id;
		this.loan_application_id = loanApplicationId;
		this.state = state;
		this.disbursed_at = disbursedAt;
		this.created_at = createdAt;
		this.updated_at = updatedAt;
		this.borrower_id = borrowerId;
		this.application_id = applicationId;
		this.overdue_penalty = overduePenalty;
		this.overdue_management_fee_rate = overdueManagementFeeRate;
		this.overdue_interest_rate = overdueInterestRate;
		this.expected_repayment_date = expectedRepaymentDate;
		this.lender_id = lenderId;
		this.closed_at = closedAt;
		this.last_payment_run_at = lastPaymentRunAt;
		this.last_past_due_at = lastPastDueAt;
		this.tenor = tenor;
		this.amount = amount;
		this.verified_bank_card = verifiedBankCard;
		this.overdue_charge_version = overdueChargeVersion;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getLoan_application_id()
	{
		return loan_application_id;
	}

	public void setLoan_application_id(Integer loan_application_id)
	{
		this.loan_application_id = loan_application_id;
	}

	public String getState()
	{
		return state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	public Date getDisbursed_at()
	{
		return disbursed_at;
	}

	public void setDisbursed_at(Date disbursed_at)
	{
		this.disbursed_at = disbursed_at;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

	public Integer getBorrower_id()
	{
		return borrower_id;
	}

	public void setBorrower_id(Integer borrower_id)
	{
		this.borrower_id = borrower_id;
	}

	public String getApplication_id()
	{
		return application_id;
	}

	public void setApplication_id(String application_id)
	{
		this.application_id = application_id;
	}

	public BigDecimal getOverdue_penalty()
	{
		return overdue_penalty;
	}

	public void setOverdue_penalty(BigDecimal overdue_penalty)
	{
		this.overdue_penalty = overdue_penalty;
	}

	public BigDecimal getOverdue_management_fee_rate()
	{
		return overdue_management_fee_rate;
	}

	public void setOverdue_management_fee_rate(BigDecimal overdue_management_fee_rate)
	{
		this.overdue_management_fee_rate = overdue_management_fee_rate;
	}

	public BigDecimal getOverdue_interest_rate()
	{
		return overdue_interest_rate;
	}

	public void setOverdue_interest_rate(BigDecimal overdue_interest_rate)
	{
		this.overdue_interest_rate = overdue_interest_rate;
	}

	public Date getExpected_repayment_date()
	{
		return expected_repayment_date;
	}

	public void setExpected_repayment_date(Date expected_repayment_date)
	{
		this.expected_repayment_date = expected_repayment_date;
	}

	public Integer getLender_id()
	{
		return lender_id;
	}

	public void setLender_id(Integer lender_id)
	{
		this.lender_id = lender_id;
	}

	public Date getClosed_at()
	{
		return closed_at;
	}

	public void setClosed_at(Date closed_at)
	{
		this.closed_at = closed_at;
	}

	public Date getLast_payment_run_at()
	{
		return last_payment_run_at;
	}

	public void setLast_payment_run_at(Date last_payment_run_at)
	{
		this.last_payment_run_at = last_payment_run_at;
	}

	public Date getLast_past_due_at()
	{
		return last_past_due_at;
	}

	public void setLast_past_due_at(Date last_past_due_at)
	{
		this.last_past_due_at = last_past_due_at;
	}

	public String getTenor()
	{
		return tenor;
	}

	public void setTenor(String tenor)
	{
		this.tenor = tenor;
	}

	public BigDecimal getAmount()
	{
		return amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public Boolean getVerified_bank_card()
	{
		return verified_bank_card;
	}

	public void setVerified_bank_card(Boolean verified_bank_card)
	{
		this.verified_bank_card = verified_bank_card;
	}

	public Integer getOverdue_charge_version()
	{
		return overdue_charge_version;
	}

	public void setOverdue_charge_version(Integer overdue_charge_version)
	{
		this.overdue_charge_version = overdue_charge_version;
	}

	public LoanApplication getLoanApplication()
	{
		return loanApplication;
	}

	public void setLoanApplication(LoanApplication loanApplication)
	{
		this.loanApplication = loanApplication;
	}

	public List<Due> getDues()
	{
		return dues;
	}

	public void setDues(List<Due> dues)
	{
		this.dues = dues;
	}

}
