package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * MoneyTransactions generated by hbm2java
 */
public class MoneyTransactions implements java.io.Serializable
{

	private int id;
	private Integer loanId;
	private String code;
	private String state;
	private BigDecimal amount;
	private BigDecimal transFeeRate;
	private BigDecimal transFee;
	private Date startAt;
	private Date submittedAt;
	private Date endAt;
	private Date createdAt;
	private Date updatedAt;
	private Integer roleFromId;
	private String roleFromType;
	private Integer roleToId;
	private String roleToType;
	private Integer yilianTransactionId;

	public MoneyTransactions()
	{}

	public MoneyTransactions(int id)
	{
		this.id = id;
	}

	public MoneyTransactions(int id, Integer loanId, String code, String state, BigDecimal amount,
			BigDecimal transFeeRate, BigDecimal transFee, Date startAt, Date submittedAt, Date endAt, Date createdAt,
			Date updatedAt, Integer roleFromId, String roleFromType, Integer roleToId, String roleToType,
			Integer yilianTransactionId)
	{
		this.id = id;
		this.loanId = loanId;
		this.code = code;
		this.state = state;
		this.amount = amount;
		this.transFeeRate = transFeeRate;
		this.transFee = transFee;
		this.startAt = startAt;
		this.submittedAt = submittedAt;
		this.endAt = endAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.roleFromId = roleFromId;
		this.roleFromType = roleFromType;
		this.roleToId = roleToId;
		this.roleToType = roleToType;
		this.yilianTransactionId = yilianTransactionId;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getLoanId()
	{
		return this.loanId;
	}

	public void setLoanId(Integer loanId)
	{
		this.loanId = loanId;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	public BigDecimal getAmount()
	{
		return this.amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public BigDecimal getTransFeeRate()
	{
		return this.transFeeRate;
	}

	public void setTransFeeRate(BigDecimal transFeeRate)
	{
		this.transFeeRate = transFeeRate;
	}

	public BigDecimal getTransFee()
	{
		return this.transFee;
	}

	public void setTransFee(BigDecimal transFee)
	{
		this.transFee = transFee;
	}

	public Date getStartAt()
	{
		return this.startAt;
	}

	public void setStartAt(Date startAt)
	{
		this.startAt = startAt;
	}

	public Date getSubmittedAt()
	{
		return this.submittedAt;
	}

	public void setSubmittedAt(Date submittedAt)
	{
		this.submittedAt = submittedAt;
	}

	public Date getEndAt()
	{
		return this.endAt;
	}

	public void setEndAt(Date endAt)
	{
		this.endAt = endAt;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public Integer getRoleFromId()
	{
		return this.roleFromId;
	}

	public void setRoleFromId(Integer roleFromId)
	{
		this.roleFromId = roleFromId;
	}

	public String getRoleFromType()
	{
		return this.roleFromType;
	}

	public void setRoleFromType(String roleFromType)
	{
		this.roleFromType = roleFromType;
	}

	public Integer getRoleToId()
	{
		return this.roleToId;
	}

	public void setRoleToId(Integer roleToId)
	{
		this.roleToId = roleToId;
	}

	public String getRoleToType()
	{
		return this.roleToType;
	}

	public void setRoleToType(String roleToType)
	{
		this.roleToType = roleToType;
	}

	public Integer getYilianTransactionId()
	{
		return this.yilianTransactionId;
	}

	public void setYilianTransactionId(Integer yilianTransactionId)
	{
		this.yilianTransactionId = yilianTransactionId;
	}

}
