package com.wolaidai.ws.jrocket2.persistence;

// Generated Jan 3, 2015 2:18:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PopActivities generated by hbm2java
 */
public class PopActivity implements java.io.Serializable
{
	private static final long serialVersionUID = 4334331563131558853L;
	private Integer id;
	private Integer pop_banner_id;
	private String content;
	private String image;
	private String url;
	private Integer priority;
	private Date start_time;
	private Date end_time;
	private Integer last_modify_by_id;
	private Integer image_version;
	private Date created_at;
	private Date updated_at;

	public PopActivity()
	{}

	public PopActivity(Integer id)
	{
		this.id = id;
	}

	public PopActivity(Integer id, Integer popBannerId, String content, String image, String url, Integer priority,
			Date startTime, Date endTime, Integer lastModifyById, Integer imageVersion, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.pop_banner_id = popBannerId;
		this.content = content;
		this.image = image;
		this.url = url;
		this.priority = priority;
		this.start_time = startTime;
		this.end_time = endTime;
		this.last_modify_by_id = lastModifyById;
		this.image_version = imageVersion;
		this.created_at = createdAt;
		this.updated_at = updatedAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getPop_banner_id()
	{
		return pop_banner_id;
	}

	public void setPop_banner_id(Integer pop_banner_id)
	{
		this.pop_banner_id = pop_banner_id;
	}

	public String getContent()
	{
		return content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getImage()
	{
		return image;
	}

	public void setImage(String image)
	{
		this.image = image;
	}

	public String getUrl()
	{
		return url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	public Integer getPriority()
	{
		return priority;
	}

	public void setPriority(Integer priority)
	{
		this.priority = priority;
	}

	public Date getStart_time()
	{
		return start_time;
	}

	public void setStart_time(Date start_time)
	{
		this.start_time = start_time;
	}

	public Date getEnd_time()
	{
		return end_time;
	}

	public void setEnd_time(Date end_time)
	{
		this.end_time = end_time;
	}

	public Integer getLast_modify_by_id()
	{
		return last_modify_by_id;
	}

	public void setLast_modify_by_id(Integer last_modify_by_id)
	{
		this.last_modify_by_id = last_modify_by_id;
	}

	public Integer getImage_version()
	{
		return image_version;
	}

	public void setImage_version(Integer image_version)
	{
		this.image_version = image_version;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

}
