package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * Profiles generated by hbm2java
 */
public class Profile implements java.io.Serializable
{

	private static final long serialVersionUID = -7573181161132832670L;
	private Integer id;
	private String name;
	private String gender;
	private Integer borrower_id;
	private String cnid;
	private Date created_at;
	private Date updated_at;
	private Boolean verified;
	private Integer education_level_id;
	private Date enter_school_date;
	private String email;
	private Integer position_id;
	private List<Addresses> addresses;
	//
	private Addresses resident_address;
	private Addresses family_address;
	private boolean locked;

	public Profile()
	{}

	public Profile(Integer id)
	{
		this.id = id;
	}

	public Profile(int id, String name, String gender, Integer borrowerId, String cnid, Date createdAt,
			Date updatedAt, Boolean verified, Integer educationLevelId, Date enterSchoolDate, String email,
			Integer positionId)
	{
		this.id = id;
		this.name = name;
		this.gender = gender;
		this.borrower_id = borrowerId;
		this.cnid = cnid;
		this.created_at = createdAt;
		this.updated_at = updatedAt;
		this.verified = verified;
		this.education_level_id = educationLevelId;
		this.enter_school_date = enterSchoolDate;
		this.email = email;
		this.position_id = positionId;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getGender()
	{
		return this.gender;
	}

	public void setGender(String gender)
	{
		this.gender = gender;
	}

	public Integer getBorrower_id()
	{
		return this.borrower_id;
	}

	public void setBorrower_id(Integer borrowerId)
	{
		this.borrower_id = borrowerId;
	}

	public String getCnid()
	{
		return this.cnid;
	}

	public void setCnid(String cnid)
	{
		this.cnid = cnid;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

	public Boolean getVerified()
	{
		return this.verified;
	}

	public void setVerified(Boolean verified)
	{
		this.verified = verified;
	}

	public Integer getEducation_level_id()
	{
		return education_level_id;
	}

	public void setEducation_level_id(Integer education_level_id)
	{
		this.education_level_id = education_level_id;
	}

	public Date getEnter_school_date()
	{
		return enter_school_date;
	}

	public void setEnter_school_date(Date enter_school_date)
	{
		this.enter_school_date = enter_school_date;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public Integer getPosition_id()
	{
		return position_id;
	}

	public void setPosition_id(Integer position_id)
	{
		this.position_id = position_id;
	}

	public List<Addresses> getAddresses()
	{
		return addresses;
	}

	public void setAddresses(List<Addresses> addresses)
	{
		this.addresses = addresses;
	}

	public Addresses getResident_address()
	{
		return resident_address;
	}

	public void setResident_address(Addresses resident_address)
	{
		this.resident_address = resident_address;
	}

	public Addresses getFamily_address()
	{
		return family_address;
	}

	public void setFamily_address(Addresses family_address)
	{
		this.family_address = family_address;
	}

	public boolean isLocked()
	{
		return locked;
	}

	public void setLocked(boolean locked)
	{
		this.locked = locked;
	}
}