package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * QqProfiles generated by hbm2java
 */
public class QqProfiles implements java.io.Serializable
{

	private int id;
	private Integer borrowerId;
	private String openId;
	private String accessToken;
	private String nickname;
	private String avatarUrl;
	private Date createdAt;
	private Date updatedAt;

	public QqProfiles()
	{}

	public QqProfiles(int id)
	{
		this.id = id;
	}

	public QqProfiles(int id, Integer borrowerId, String openId, String accessToken, String nickname, String avatarUrl,
			Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.borrowerId = borrowerId;
		this.openId = openId;
		this.accessToken = accessToken;
		this.nickname = nickname;
		this.avatarUrl = avatarUrl;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getBorrowerId()
	{
		return this.borrowerId;
	}

	public void setBorrowerId(Integer borrowerId)
	{
		this.borrowerId = borrowerId;
	}

	public String getOpenId()
	{
		return this.openId;
	}

	public void setOpenId(String openId)
	{
		this.openId = openId;
	}

	public String getAccessToken()
	{
		return this.accessToken;
	}

	public void setAccessToken(String accessToken)
	{
		this.accessToken = accessToken;
	}

	public String getNickname()
	{
		return this.nickname;
	}

	public void setNickname(String nickname)
	{
		this.nickname = nickname;
	}

	public String getAvatarUrl()
	{
		return this.avatarUrl;
	}

	public void setAvatarUrl(String avatarUrl)
	{
		this.avatarUrl = avatarUrl;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
