package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * SchemaMigrations generated by hbm2java
 */
public class SchemaMigrations implements java.io.Serializable
{

	private String version;

	public SchemaMigrations()
	{}

	public SchemaMigrations(String version)
	{
		this.version = version;
	}

	public String getVersion()
	{
		return this.version;
	}

	public void setVersion(String version)
	{
		this.version = version;
	}

}
