package com.wolaidai.ws.jrocket2.persistence;

// Generated Jan 3, 2015 2:18:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Schools generated by hbm2java
 */
public class School implements java.io.Serializable
{
	private static final long serialVersionUID = 8683686085266088595L;
	private Integer id;
	private String name;
	private String category1;
	private String province;
	private String category2;
	private String locale;
	private String city;
	private String category3;
	private Boolean isCollege;
	private Date createdAt;
	private Date updatedAt;

	public School()
	{}

	public School(Integer id)
	{
		this.id = id;
	}

	public School(Integer id, String name, String category1, String province, String category2, String locale,
			String city, String category3, Boolean isCollege, Date createdAt, Date updatedAt)
	{
		this.id = id;
		this.name = name;
		this.category1 = category1;
		this.province = province;
		this.category2 = category2;
		this.locale = locale;
		this.city = city;
		this.category3 = category3;
		this.isCollege = isCollege;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getCategory1()
	{
		return this.category1;
	}

	public void setCategory1(String category1)
	{
		this.category1 = category1;
	}

	public String getProvince()
	{
		return this.province;
	}

	public void setProvince(String province)
	{
		this.province = province;
	}

	public String getCategory2()
	{
		return this.category2;
	}

	public void setCategory2(String category2)
	{
		this.category2 = category2;
	}

	public String getLocale()
	{
		return this.locale;
	}

	public void setLocale(String locale)
	{
		this.locale = locale;
	}

	public String getCity()
	{
		return this.city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	public String getCategory3()
	{
		return this.category3;
	}

	public void setCategory3(String category3)
	{
		this.category3 = category3;
	}

	public Boolean getIsCollege()
	{
		return this.isCollege;
	}

	public void setIsCollege(Boolean isCollege)
	{
		this.isCollege = isCollege;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

}
