package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StudentDetails generated by hbm2java
 */
public class StudentDetails implements java.io.Serializable
{

	private int id;
	private String schoolName;
	private String homeStreet;
	private String homePhone;
	private Integer loanApplicationId;
	private Date createdAt;
	private Date updatedAt;
	private Integer homeDistrictId;

	public StudentDetails()
	{}

	public StudentDetails(int id)
	{
		this.id = id;
	}

	public StudentDetails(int id, String schoolName, String homeStreet, String homePhone, Integer loanApplicationId,
			Date createdAt, Date updatedAt, Integer homeDistrictId)
	{
		this.id = id;
		this.schoolName = schoolName;
		this.homeStreet = homeStreet;
		this.homePhone = homePhone;
		this.loanApplicationId = loanApplicationId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.homeDistrictId = homeDistrictId;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getSchoolName()
	{
		return this.schoolName;
	}

	public void setSchoolName(String schoolName)
	{
		this.schoolName = schoolName;
	}

	public String getHomeStreet()
	{
		return this.homeStreet;
	}

	public void setHomeStreet(String homeStreet)
	{
		this.homeStreet = homeStreet;
	}

	public String getHomePhone()
	{
		return this.homePhone;
	}

	public void setHomePhone(String homePhone)
	{
		this.homePhone = homePhone;
	}

	public Integer getLoanApplicationId()
	{
		return this.loanApplicationId;
	}

	public void setLoanApplicationId(Integer loanApplicationId)
	{
		this.loanApplicationId = loanApplicationId;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public Integer getHomeDistrictId()
	{
		return this.homeDistrictId;
	}

	public void setHomeDistrictId(Integer homeDistrictId)
	{
		this.homeDistrictId = homeDistrictId;
	}

}
