package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TradeApplications generated by hbm2java
 */
public class TradeApplication implements java.io.Serializable
{
	private static final long serialVersionUID = -5971124878440311180L;
	public static final String ACTION_WITHDRAW = "withdraw";
	public static final String ACTION_TOPUP = "topup";

	public enum State
	{
		APPLIED("applied"), APPROVED("approved"), FAILED("failed"), SUCCEED("succeed");

		private String m_value;

		private State(String value)
		{
			m_value = value;
		}

		public String getValue()
		{
			return m_value;
		}
	}

	private Integer id;
	private Integer account_id;
	private Integer operator_id;
	private BigDecimal amount;
	private BigDecimal fee;
	private String action;
	private String state;
	private Date operated_at;
	private Date created_at;
	private Date updated_at;
	private Integer bank_card_id;

	public TradeApplication()
	{}

	public TradeApplication(Integer id)
	{
		this.id = id;
	}

	public TradeApplication(Integer id, Integer accountId, Integer operatorId, BigDecimal amount, BigDecimal fee,
			String action, String state, Date operatedAt, Date createdAt, Date updatedAt, Integer bankCardId)
	{
		this.id = id;
		this.account_id = accountId;
		this.operator_id = operatorId;
		this.amount = amount;
		this.fee = fee;
		this.action = action;
		this.state = state;
		this.operated_at = operatedAt;
		this.created_at = createdAt;
		this.updated_at = updatedAt;
		this.bank_card_id = bankCardId;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public BigDecimal getAmount()
	{
		return this.amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public BigDecimal getFee()
	{
		return this.fee;
	}

	public void setFee(BigDecimal fee)
	{
		this.fee = fee;
	}

	public String getAction()
	{
		return this.action;
	}

	public void setAction(String action)
	{
		this.action = action;
	}

	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	public Integer getAccount_id()
	{
		return account_id;
	}

	public void setAccount_id(Integer account_id)
	{
		this.account_id = account_id;
	}

	public Integer getOperator_id()
	{
		return operator_id;
	}

	public void setOperator_id(Integer operator_id)
	{
		this.operator_id = operator_id;
	}

	public Date getOperated_at()
	{
		return operated_at;
	}

	public void setOperated_at(Date operated_at)
	{
		this.operated_at = operated_at;
	}

	public Date getCreated_at()
	{
		return created_at;
	}

	public void setCreated_at(Date created_at)
	{
		this.created_at = created_at;
	}

	public Date getUpdated_at()
	{
		return updated_at;
	}

	public void setUpdated_at(Date updated_at)
	{
		this.updated_at = updated_at;
	}

	public Integer getBank_card_id()
	{
		return bank_card_id;
	}

	public void setBank_card_id(Integer bank_card_id)
	{
		this.bank_card_id = bank_card_id;
	}

}
