package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1
// Updated Jan 3, 2015 2:16 PM by space.wen@wolaidai.com

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class User implements java.io.Serializable
{
	private static final long serialVersionUID = -6808678673536644130L;
	private Integer id;
	private String mobile;
	private String encryptedPassword;
	private String resetPasswordToken;
	private Date resetPasswordSentAt;
	private int signInCount;
	private Date currentSignInAt;
	private Date lastSignInAt;
	private String currentSignInIp;
	private String lastSignInIp;
	private Date confirmedAt;
	private int failedAttempts;
	private String unlockToken;
	private Date lockedAt;
	private Date createdAt;
	private Date updatedAt;
	private String authenticationToken;
	private String screenName;
	private String memberId;
	private Boolean blocked;
	private Boolean toReceiveNewsletter;
	private String email;
	private Date emailConfirmed;
	private String deviceInfo;
	private String encryptedSecurityCode;
	private String userAgent;
	private String origin;
	private Boolean agent;
	private Integer referee_id;
	private Profile profile;

	public User()
	{}

	public User(Integer id)
	{
		this.id = id;
	}

	public User(Integer id, String mobile, String encryptedPassword, int signInCount, int failedAttempts,
			String memberId)
	{
		this.id = id;
		this.mobile = mobile;
		this.encryptedPassword = encryptedPassword;
		this.signInCount = signInCount;
		this.failedAttempts = failedAttempts;
		this.memberId = memberId;
	}

	public User(Integer id, String mobile, String encryptedPassword, String resetPasswordToken,
			Date resetPasswordSentAt, int signInCount, Date currentSignInAt, Date lastSignInAt, String currentSignInIp,
			String lastSignInIp, Date confirmedAt, int failedAttempts, String unlockToken, Date lockedAt,
			Date createdAt, Date updatedAt, String authenticationToken, String screenName, String memberId,
			Boolean blocked, Boolean toReceiveNewsletter, String email, Date emailConfirmed, String deviceInfo,
			String encryptedSecurityCode, String userAgent)
	{
		this.id = id;
		this.mobile = mobile;
		this.encryptedPassword = encryptedPassword;
		this.resetPasswordToken = resetPasswordToken;
		this.resetPasswordSentAt = resetPasswordSentAt;
		this.signInCount = signInCount;
		this.currentSignInAt = currentSignInAt;
		this.lastSignInAt = lastSignInAt;
		this.currentSignInIp = currentSignInIp;
		this.lastSignInIp = lastSignInIp;
		this.confirmedAt = confirmedAt;
		this.failedAttempts = failedAttempts;
		this.unlockToken = unlockToken;
		this.lockedAt = lockedAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.authenticationToken = authenticationToken;
		this.screenName = screenName;
		this.memberId = memberId;
		this.blocked = blocked;
		this.toReceiveNewsletter = toReceiveNewsletter;
		this.email = email;
		this.emailConfirmed = emailConfirmed;
		this.deviceInfo = deviceInfo;
		this.encryptedSecurityCode = encryptedSecurityCode;
		this.userAgent = userAgent;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getEncryptedPassword()
	{
		return this.encryptedPassword;
	}

	public void setEncryptedPassword(String encryptedPassword)
	{
		this.encryptedPassword = encryptedPassword;
	}

	public String getResetPasswordToken()
	{
		return this.resetPasswordToken;
	}

	public void setResetPasswordToken(String resetPasswordToken)
	{
		this.resetPasswordToken = resetPasswordToken;
	}

	public Date getResetPasswordSentAt()
	{
		return this.resetPasswordSentAt;
	}

	public void setResetPasswordSentAt(Date resetPasswordSentAt)
	{
		this.resetPasswordSentAt = resetPasswordSentAt;
	}

	public int getSignInCount()
	{
		return this.signInCount;
	}

	public void setSignInCount(int signInCount)
	{
		this.signInCount = signInCount;
	}

	public Date getCurrentSignInAt()
	{
		return this.currentSignInAt;
	}

	public void setCurrentSignInAt(Date currentSignInAt)
	{
		this.currentSignInAt = currentSignInAt;
	}

	public Date getLastSignInAt()
	{
		return this.lastSignInAt;
	}

	public void setLastSignInAt(Date lastSignInAt)
	{
		this.lastSignInAt = lastSignInAt;
	}

	public String getCurrentSignInIp()
	{
		return this.currentSignInIp;
	}

	public void setCurrentSignInIp(String currentSignInIp)
	{
		this.currentSignInIp = currentSignInIp;
	}

	public String getLastSignInIp()
	{
		return this.lastSignInIp;
	}

	public void setLastSignInIp(String lastSignInIp)
	{
		this.lastSignInIp = lastSignInIp;
	}

	public Date getConfirmedAt()
	{
		return this.confirmedAt;
	}

	public void setConfirmedAt(Date confirmedAt)
	{
		this.confirmedAt = confirmedAt;
	}

	public int getFailedAttempts()
	{
		return this.failedAttempts;
	}

	public void setFailedAttempts(int failedAttempts)
	{
		this.failedAttempts = failedAttempts;
	}

	public String getUnlockToken()
	{
		return this.unlockToken;
	}

	public void setUnlockToken(String unlockToken)
	{
		this.unlockToken = unlockToken;
	}

	public Date getLockedAt()
	{
		return this.lockedAt;
	}

	public void setLockedAt(Date lockedAt)
	{
		this.lockedAt = lockedAt;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public String getAuthenticationToken()
	{
		return this.authenticationToken;
	}

	public void setAuthenticationToken(String authenticationToken)
	{
		this.authenticationToken = authenticationToken;
	}

	public String getScreenName()
	{
		return this.screenName;
	}

	public void setScreenName(String screenName)
	{
		this.screenName = screenName;
	}

	public String getMemberId()
	{
		return this.memberId;
	}

	public void setMemberId(String memberId)
	{
		this.memberId = memberId;
	}

	public Boolean getBlocked()
	{
		return this.blocked;
	}

	public void setBlocked(Boolean blocked)
	{
		this.blocked = blocked;
	}

	public Boolean getToReceiveNewsletter()
	{
		return this.toReceiveNewsletter;
	}

	public void setToReceiveNewsletter(Boolean toReceiveNewsletter)
	{
		this.toReceiveNewsletter = toReceiveNewsletter;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public Date getEmailConfirmed()
	{
		return this.emailConfirmed;
	}

	public void setEmailConfirmed(Date emailConfirmed)
	{
		this.emailConfirmed = emailConfirmed;
	}

	public String getDeviceInfo()
	{
		return this.deviceInfo;
	}

	public void setDeviceInfo(String deviceInfo)
	{
		this.deviceInfo = deviceInfo;
	}

	public String getEncryptedSecurityCode()
	{
		return this.encryptedSecurityCode;
	}

	public void setEncryptedSecurityCode(String encryptedSecurityCode)
	{
		this.encryptedSecurityCode = encryptedSecurityCode;
	}

	public String getUserAgent()
	{
		return this.userAgent;
	}

	public void setUserAgent(String userAgent)
	{
		this.userAgent = userAgent;
	}

	public String getOrigin()
	{
		return origin;
	}

	public void setOrigin(String origin)
	{
		this.origin = origin;
	}

	public Boolean getAgent()
	{
		return agent;
	}

	public void setAgent(Boolean agent)
	{
		this.agent = agent;
	}

	public Integer getReferee_id()
	{
		return referee_id;
	}

	public void setReferee_id(Integer referee_id)
	{
		this.referee_id = referee_id;
	}

	public Profile getProfile()
	{
		return profile;
	}

	public void setProfile(Profile profile)
	{
		this.profile = profile;
	}

}
