package com.wolaidai.ws.jrocket2.persistence;

// Generated Dec 16, 2014 8:09:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * YilianTransactions generated by hbm2java
 */
public class YilianTransactions implements java.io.Serializable
{

	private int id;
	private String msgType;
	private String batchNo;
	private String userName;
	private String transState;
	private String payState;
	private String bankId;
	private String accNo;
	private String accName;
	private String accProvince;
	private String accCity;
	private String idNo;
	private String mobileNo;
	private BigDecimal amount;
	private Date createdAt;
	private Date updatedAt;
	private Integer loanId;
	private String code;
	private BigDecimal transFeeRate;
	private BigDecimal transFee;
	private Integer roleId;
	private String roleType;
	private String remark;
	private String successDate;
	private Integer tradeApplicationId;
	private Integer bankCardId;

	public YilianTransactions()
	{}

	public YilianTransactions(int id)
	{
		this.id = id;
	}

	public YilianTransactions(int id, String msgType, String batchNo, String userName, String transState,
			String payState, String bankId, String accNo, String accName, String accProvince, String accCity,
			String idNo, String mobileNo, BigDecimal amount, Date createdAt, Date updatedAt, Integer loanId,
			String code, BigDecimal transFeeRate, BigDecimal transFee, Integer roleId, String roleType, String remark,
			String successDate, Integer tradeApplicationId, Integer bankCardId)
	{
		this.id = id;
		this.msgType = msgType;
		this.batchNo = batchNo;
		this.userName = userName;
		this.transState = transState;
		this.payState = payState;
		this.bankId = bankId;
		this.accNo = accNo;
		this.accName = accName;
		this.accProvince = accProvince;
		this.accCity = accCity;
		this.idNo = idNo;
		this.mobileNo = mobileNo;
		this.amount = amount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.loanId = loanId;
		this.code = code;
		this.transFeeRate = transFeeRate;
		this.transFee = transFee;
		this.roleId = roleId;
		this.roleType = roleType;
		this.remark = remark;
		this.successDate = successDate;
		this.tradeApplicationId = tradeApplicationId;
		this.bankCardId = bankCardId;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getMsgType()
	{
		return this.msgType;
	}

	public void setMsgType(String msgType)
	{
		this.msgType = msgType;
	}

	public String getBatchNo()
	{
		return this.batchNo;
	}

	public void setBatchNo(String batchNo)
	{
		this.batchNo = batchNo;
	}

	public String getUserName()
	{
		return this.userName;
	}

	public void setUserName(String userName)
	{
		this.userName = userName;
	}

	public String getTransState()
	{
		return this.transState;
	}

	public void setTransState(String transState)
	{
		this.transState = transState;
	}

	public String getPayState()
	{
		return this.payState;
	}

	public void setPayState(String payState)
	{
		this.payState = payState;
	}

	public String getBankId()
	{
		return this.bankId;
	}

	public void setBankId(String bankId)
	{
		this.bankId = bankId;
	}

	public String getAccNo()
	{
		return this.accNo;
	}

	public void setAccNo(String accNo)
	{
		this.accNo = accNo;
	}

	public String getAccName()
	{
		return this.accName;
	}

	public void setAccName(String accName)
	{
		this.accName = accName;
	}

	public String getAccProvince()
	{
		return this.accProvince;
	}

	public void setAccProvince(String accProvince)
	{
		this.accProvince = accProvince;
	}

	public String getAccCity()
	{
		return this.accCity;
	}

	public void setAccCity(String accCity)
	{
		this.accCity = accCity;
	}

	public String getIdNo()
	{
		return this.idNo;
	}

	public void setIdNo(String idNo)
	{
		this.idNo = idNo;
	}

	public String getMobileNo()
	{
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo)
	{
		this.mobileNo = mobileNo;
	}

	public BigDecimal getAmount()
	{
		return this.amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public Integer getLoanId()
	{
		return this.loanId;
	}

	public void setLoanId(Integer loanId)
	{
		this.loanId = loanId;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public BigDecimal getTransFeeRate()
	{
		return this.transFeeRate;
	}

	public void setTransFeeRate(BigDecimal transFeeRate)
	{
		this.transFeeRate = transFeeRate;
	}

	public BigDecimal getTransFee()
	{
		return this.transFee;
	}

	public void setTransFee(BigDecimal transFee)
	{
		this.transFee = transFee;
	}

	public Integer getRoleId()
	{
		return this.roleId;
	}

	public void setRoleId(Integer roleId)
	{
		this.roleId = roleId;
	}

	public String getRoleType()
	{
		return this.roleType;
	}

	public void setRoleType(String roleType)
	{
		this.roleType = roleType;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	public String getSuccessDate()
	{
		return this.successDate;
	}

	public void setSuccessDate(String successDate)
	{
		this.successDate = successDate;
	}

	public Integer getTradeApplicationId()
	{
		return this.tradeApplicationId;
	}

	public void setTradeApplicationId(Integer tradeApplicationId)
	{
		this.tradeApplicationId = tradeApplicationId;
	}

	public Integer getBankCardId()
	{
		return this.bankCardId;
	}

	public void setBankCardId(Integer bankCardId)
	{
		this.bankCardId = bankCardId;
	}

}
