package com.welab.finance.core.model;

// Generated Jan 13, 2015 5:05:42 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Disbursereport generated by hbm2java
 */
public class Disbursereport implements java.io.Serializable
{

	private Date rptdate;
	private int disbursetotalcount;
	private BigDecimal disbursetotalamount;
	private int withdrawtotalcount;
	private BigDecimal withdrawtotalamount;
	private int withdrawfailcount;
	private BigDecimal withdrawfailamount;

	public Disbursereport()
	{}

	public Disbursereport(Date rptdate, int disbursetotalcount, BigDecimal disbursetotalamount, int withdrawtotalcount,
			BigDecimal withdrawtotalamount, int withdrawfailcount, BigDecimal withdrawfailamount)
	{
		this.rptdate = rptdate;
		this.disbursetotalcount = disbursetotalcount;
		this.disbursetotalamount = disbursetotalamount;
		this.withdrawtotalcount = withdrawtotalcount;
		this.withdrawtotalamount = withdrawtotalamount;
		this.withdrawfailcount = withdrawfailcount;
		this.withdrawfailamount = withdrawfailamount;
	}

	public Date getRptdate()
	{
		return this.rptdate;
	}

	public void setRptdate(Date rptdate)
	{
		this.rptdate = rptdate;
	}

	public int getDisbursetotalcount()
	{
		return this.disbursetotalcount;
	}

	public void setDisbursetotalcount(int disbursetotalcount)
	{
		this.disbursetotalcount = disbursetotalcount;
	}

	public BigDecimal getDisbursetotalamount()
	{
		return this.disbursetotalamount;
	}

	public void setDisbursetotalamount(BigDecimal disbursetotalamount)
	{
		this.disbursetotalamount = disbursetotalamount;
	}

	public int getWithdrawtotalcount()
	{
		return this.withdrawtotalcount;
	}

	public void setWithdrawtotalcount(int withdrawtotalcount)
	{
		this.withdrawtotalcount = withdrawtotalcount;
	}

	public BigDecimal getWithdrawtotalamount()
	{
		return this.withdrawtotalamount;
	}

	public void setWithdrawtotalamount(BigDecimal withdrawtotalamount)
	{
		this.withdrawtotalamount = withdrawtotalamount;
	}

	public int getWithdrawfailcount()
	{
		return this.withdrawfailcount;
	}

	public void setWithdrawfailcount(int withdrawfailcount)
	{
		this.withdrawfailcount = withdrawfailcount;
	}

	public BigDecimal getWithdrawfailamount()
	{
		return this.withdrawfailamount;
	}

	public void setWithdrawfailamount(BigDecimal withdrawfailamount)
	{
		this.withdrawfailamount = withdrawfailamount;
	}

}
