package com.welab.finance.core.model;

// Generated Jan 13, 2015 5:05:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable
{

	private int id;
	private String role;
	private Date createdat;
	private Date updatedat;
	private String description;

	public Roles()
	{}

	public Roles(int id)
	{
		this.id = id;
	}

	public Roles(int id, String role, Date createdat, Date updatedat, String description)
	{
		this.id = id;
		this.role = role;
		this.createdat = createdat;
		this.updatedat = updatedat;
		this.description = description;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getRole()
	{
		return this.role;
	}

	public void setRole(String role)
	{
		this.role = role;
	}

	public Date getCreatedat()
	{
		return this.createdat;
	}

	public void setCreatedat(Date createdat)
	{
		this.createdat = createdat;
	}

	public Date getUpdatedat()
	{
		return this.updatedat;
	}

	public void setUpdatedat(Date updatedat)
	{
		this.updatedat = updatedat;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

}
