package com.welab.finance.core.model;

// Generated Jan 12, 2015 2:33:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable
{

	private int id;
	private String role;
	private Date createdAt;
	private Date updatedAt;
	private String description;

	public Roles()
	{}

	public Roles(int id)
	{
		this.id = id;
	}

	public Roles(int id, String role, Date createdAt, Date updatedAt, String description)
	{
		this.id = id;
		this.role = role;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.description = description;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getRole()
	{
		return this.role;
	}

	public void setRole(String role)
	{
		this.role = role;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

}
