package com.welab.finance.core.model;

// Generated Jan 12, 2015 2:33:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable
{

	private int id;
	private String name;
	private String roleId;
	private String email;
	private String encryptedPassword;
	private Date createdAt;
	private Date updatedAt;
	private int signInCount;
	private Date currentSignInAt;
	private String currentSignInIp;
	private Boolean locked;
	private int failedAttempts;
	private Date lockedAt;

	public Users()
	{}

	public Users(int id, String roleId, String email, String encryptedPassword, int signInCount, int failedAttempts)
	{
		this.id = id;
		this.roleId = roleId;
		this.email = email;
		this.encryptedPassword = encryptedPassword;
		this.signInCount = signInCount;
		this.failedAttempts = failedAttempts;
	}

	public Users(int id, String name, String roleId, String email, String encryptedPassword, Date createdAt,
			Date updatedAt, int signInCount, Date currentSignInAt, String currentSignInIp, Boolean locked,
			int failedAttempts, Date lockedAt)
	{
		this.id = id;
		this.name = name;
		this.roleId = roleId;
		this.email = email;
		this.encryptedPassword = encryptedPassword;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.signInCount = signInCount;
		this.currentSignInAt = currentSignInAt;
		this.currentSignInIp = currentSignInIp;
		this.locked = locked;
		this.failedAttempts = failedAttempts;
		this.lockedAt = lockedAt;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getRoleId()
	{
		return this.roleId;
	}

	public void setRoleId(String roleId)
	{
		this.roleId = roleId;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getEncryptedPassword()
	{
		return this.encryptedPassword;
	}

	public void setEncryptedPassword(String encryptedPassword)
	{
		this.encryptedPassword = encryptedPassword;
	}

	public Date getCreatedAt()
	{
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt()
	{
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt)
	{
		this.updatedAt = updatedAt;
	}

	public int getSignInCount()
	{
		return this.signInCount;
	}

	public void setSignInCount(int signInCount)
	{
		this.signInCount = signInCount;
	}

	public Date getCurrentSignInAt()
	{
		return this.currentSignInAt;
	}

	public void setCurrentSignInAt(Date currentSignInAt)
	{
		this.currentSignInAt = currentSignInAt;
	}

	public String getCurrentSignInIp()
	{
		return this.currentSignInIp;
	}

	public void setCurrentSignInIp(String currentSignInIp)
	{
		this.currentSignInIp = currentSignInIp;
	}

	public Boolean getLocked()
	{
		return this.locked;
	}

	public void setLocked(Boolean locked)
	{
		this.locked = locked;
	}

	public int getFailedAttempts()
	{
		return this.failedAttempts;
	}

	public void setFailedAttempts(int failedAttempts)
	{
		this.failedAttempts = failedAttempts;
	}

	public Date getLockedAt()
	{
		return this.lockedAt;
	}

	public void setLockedAt(Date lockedAt)
	{
		this.lockedAt = lockedAt;
	}

}
