package com.welab.finance.core.model;

// Generated Jan 13, 2015 5:05:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Users generated by hbm2java
 */
public class User implements java.io.Serializable
{

	private Integer id;
	private String name;
	private String mobile;
	private String roleid;
	private String email;
	private String encryptedpassword;
	private Date createdat;
	private Date updatedat;
	private int signincount;
	private Date currentsigninat;
	private String currentsigninip;
	private Boolean locked;
	private int failedattempts;
	private Date lockedat;

	public User()
	{}

	public User(Integer id, String name, String roleid, String email, String encryptedpassword, int signincount,
			int failedattempts)
	{
		this.id = id;
		this.name = name;
		this.roleid = roleid;
		this.email = email;
		this.encryptedpassword = encryptedpassword;
		this.signincount = signincount;
		this.failedattempts = failedattempts;
	}

	public User(int id, String name, String mobile, String roleid, String email, String encryptedpassword,
			Date createdat, Date updatedat, int signincount, Date currentsigninat, String currentsigninip,
			Boolean locked, int failedattempts, Date lockedat)
	{
		this.id = id;
		this.name = name;
		this.mobile = mobile;
		this.roleid = roleid;
		this.email = email;
		this.encryptedpassword = encryptedpassword;
		this.createdat = createdat;
		this.updatedat = updatedat;
		this.signincount = signincount;
		this.currentsigninat = currentsigninat;
		this.currentsigninip = currentsigninip;
		this.locked = locked;
		this.failedattempts = failedattempts;
		this.lockedat = lockedat;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@NotEmpty(message = "用户名不能为空")
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getRoleid()
	{
		return this.roleid;
	}

	public void setRoleid(String roleid)
	{
		this.roleid = roleid;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	@Length(min = 1, max = 8, message = "长度必须在1到8之间")
	public String getEncryptedpassword()
	{
		return this.encryptedpassword;
	}

	public void setEncryptedpassword(String encryptedpassword)
	{
		this.encryptedpassword = encryptedpassword;
	}

	public Date getCreatedat()
	{
		return this.createdat;
	}

	public void setCreatedat(Date createdat)
	{
		this.createdat = createdat;
	}

	public Date getUpdatedat()
	{
		return this.updatedat;
	}

	public void setUpdatedat(Date updatedat)
	{
		this.updatedat = updatedat;
	}

	public int getSignincount()
	{
		return this.signincount;
	}

	public void setSignincount(int signincount)
	{
		this.signincount = signincount;
	}

	public Date getCurrentsigninat()
	{
		return this.currentsigninat;
	}

	public void setCurrentsigninat(Date currentsigninat)
	{
		this.currentsigninat = currentsigninat;
	}

	public String getCurrentsigninip()
	{
		return this.currentsigninip;
	}

	public void setCurrentsigninip(String currentsigninip)
	{
		this.currentsigninip = currentsigninip;
	}

	public Boolean getLocked()
	{
		return this.locked;
	}

	public void setLocked(Boolean locked)
	{
		this.locked = locked;
	}

	public int getFailedattempts()
	{
		return this.failedattempts;
	}

	public void setFailedattempts(int failedattempts)
	{
		this.failedattempts = failedattempts;
	}

	public Date getLockedat()
	{
		return this.lockedat;
	}

	public void setLockedat(Date lockedat)
	{
		this.lockedat = lockedat;
	}

}
